package de.norm.events.genretag

import org.springframework.modulith.ApplicationModule

/**
 * Module metadata declaring the genre tag module's allowed dependencies.
 *
 * Genre tags are standalone entities, and the only module they reach is `common`, for the paged
 * response envelope. A genre tag's slug is generated by `AssociationSyncService` in the `scraper`
 * module, which declares `slug` itself.
 */
@ApplicationModule(allowedDependencies = ["common"])
class GenreTagModule
