/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List venues with pagination, name search and filters, sorted by name or by events in the next 30 days
         * @description Sort with `sort=name` (A–Z, case-folded), `sort=name,desc` (Z–A) or `sort=upcomingEvents,desc` (events that start within the next 30 days, Berlin time). A chosen sort applies with a search too. Without a sort, a search lists the closest names first, else A–Z.
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single venue by slug */
        get: operations["findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/feature-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * For each feature (character tag), how many venues match the given filters with that feature added
         * @description Takes the list's filters without paging. A feature that no matching venue carries is absent, which means 0.
         */
        get: operations["featureCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sitemaps/{kind}.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the detail pages of one kind worth crawling, in both locales, as a sitemap */
        get: operations["sitemap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The first matches of each kind for a search term */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/promoters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List promoters with pagination and optional name search, sorted by name or by events in the next 30 days
         * @description Sort with `sort=name` (A–Z, case-folded), `sort=name,desc` (Z–A) or `sort=upcomingEvents,desc` (events that start within the next 30 days, Berlin time). A chosen sort applies with a search too. Without a sort, a search lists the closest names first, else A–Z.
         */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/promoters/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single promoter by slug */
        get: operations["findBySlug_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report the version and commit of the running backend */
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{contentHash}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a cached venue image at one width and format */
        get: operations["serve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all genre tags alphabetically */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search events with optional filters and pagination
         * @description Sort with `sort=eventDate` (the default, then the start time), `sort=startTime`, `sort=title`, `sort=pricePresale` or `sort=createdAt,desc` (newest added first, when the importer first stored the event). Without a date range, the list holds only events that have not ended.
         */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single event by slug */
        get: operations["findBySlug_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{slug}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get upcoming events like one event
         * @description Up to four events that have not ended and share artists, the venue or genre tags with the event, best match first. A shared artist counts most, then the venue, then each shared genre tag. Empty when nothing matches; 404 when the slug is unknown.
         */
        get: operations["related"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get today's events */
        get: operations["today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the newest events as an RSS 2.0 feed, at most 50, leaving out those that are over */
        get: operations["feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get events within an inclusive date range for the calendar view, with the same optional filters as the search endpoint */
        get: operations["calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the events from today for 90 days as an iCalendar (RFC 5545) subscription, at most 500, in the list's order */
        get: operations["calendar_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List artists with pagination and optional name search, sorted by name
         * @description Sort with `sort=name` (A–Z, case-folded). A chosen sort applies with a search too. Without a sort, a search lists the closest names first, else A–Z.
         */
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single artist by slug */
        get: operations["findBySlug_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One format of a cached image, for a <source> element inside <picture> */
        ImageSourceResponse: {
            /**
             * @description Media type for the `type` attribute
             * @example image/avif
             */
            type?: string;
            /**
             * @description Candidate URLs and their widths, for the `srcset` attribute
             * @example /api/images/0f4b…/192.avif 192w, /api/images/0f4b…/288.avif 288w
             */
            srcset?: string;
        };
        /** @description A page of results with pagination metadata */
        PageResponseVenueListItemResponse: {
            /** @description The items on this page */
            content?: components["schemas"]["VenueListItemResponse"][];
            /**
             * Format: int32
             * @description Zero-based index of this page
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 20
             */
            size?: number;
            /**
             * Format: int64
             * @description Total number of matching items across all pages
             * @example 137
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description Total number of pages
             * @example 7
             */
            totalPages?: number;
        };
        /** @description Venue on the venue list */
        VenueListItemResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 42
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example astra-kulturhaus
             */
            slug?: string;
            /**
             * @description Display name of the venue
             * @example Astra Kulturhaus
             */
            name?: string;
            /**
             * @description City where the venue is located
             * @example Berlin
             */
            city?: string;
            /**
             * @description Street address of the venue
             * @example Revaler Str. 99
             */
            address?: string | null;
            /**
             * @description Berlin district (one of the 23 pre-2001 Bezirke) as a canonical slug
             * @example kreuzberg
             */
            district?: string | null;
            /**
             * @description Geographic latitude for map display
             * @example 52.507242
             */
            latitude?: number | null;
            /**
             * @description Geographic longitude for map display
             * @example 13.451803
             */
            longitude?: number | null;
            /** @description URL of the venue's logo or photo */
            imageUrl?: string | null;
            /**
             * @description Who to credit for `imageUrl`, worded as the archive publishes it. Present whenever `imageUrl` is, and it must be shown beside the image.
             * @example Photographer Name, via Wikimedia Commons
             */
            imageAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `imageUrl` is published under, or `PD` where no identifier applies. Example values: `CC0-1.0`, `CC-BY-4.0`, `CC-BY-SA-4.0`.
             * @example CC-BY-SA-4.0
             */
            imageLicenceId?: string | null;
            /**
             * @description The image's description page, which the rendered credit links to
             * @example https://commons.wikimedia.org/wiki/File:Example.jpg
             */
            imageSourceUrl?: string | null;
            /** @description Alternative formats of the same image, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
            /**
             * Format: int32
             * @description Events from today on at this venue
             * @example 220
             */
            upcomingEventCount?: number;
            /**
             * Format: int32
             * @description Events at this venue that start within the next 30 days, Berlin time. The list's `upcomingEvents` sort orders by this count.
             * @example 12
             */
            upcomingNext30DaysCount?: number;
            /**
             * @description What kind of place this is, as venue type slugs, curated by hand. Empty until curated.
             * @example [
             *       "live-venue",
             *       "club"
             *     ]
             */
            venueTypes?: string[];
            /**
             * Format: int32
             * @description How many visitors the largest room holds, as the venue publishes it. Null where it does not.
             * @example 1500
             */
            capacity?: number | null;
            /**
             * @description Genre family slugs the venue mostly programmes, most frequent first, derived from its events of the last year and ahead.
             * @example [
             *       "rock",
             *       "punk"
             *     ]
             */
            programmeFamilies?: string[];
            /**
             * @description Event types the venue hosts, most frequent first, derived from its events like `programmeFamilies`.
             * @example [
             *       "CONCERT",
             *       "PARTY"
             *     ]
             */
            programmeEventTypes?: string[];
            /**
             * @description What the venue says about itself (its kind of space, its door, its access), as character tag slugs, ordered by slug. Set only where the venue's own page states it.
             * @example [
             *       "queer",
             *       "awareness-team"
             *     ]
             */
            characterTags?: string[];
            /**
             * @description Whether we import this venue's events. False for a venue we know but do not import yet: it has no events here, and its page links to its programme.
             * @example true
             */
            imported?: boolean;
        };
        /** @description A character tag and the venue's own page that states it */
        VenueCharacterTagResponse: {
            /**
             * @description Character tag slug
             * @example queer
             */
            tag?: string;
            /**
             * @description URL of the venue's own page that states the tag
             * @example https://www.so36.com/about
             */
            sourceUrl?: string;
        };
        /** @description Full venue detail */
        VenueDetailResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 42
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example astra-kulturhaus
             */
            slug?: string;
            /**
             * @description Display name of the venue
             * @example Astra Kulturhaus
             */
            name?: string;
            /**
             * @description Street address of the venue
             * @example Revaler Str. 99
             */
            address?: string | null;
            /**
             * @description City where the venue is located
             * @example Berlin
             */
            city?: string;
            /**
             * @description Postal code of the venue's address
             * @example 10245
             */
            postalCode?: string | null;
            /**
             * @description Berlin district (one of the 23 pre-2001 Bezirke) as a canonical slug
             * @example kreuzberg
             */
            district?: string | null;
            /**
             * @description Geographic latitude for map display
             * @example 52.507242
             */
            latitude?: number | null;
            /**
             * @description Geographic longitude for map display
             * @example 13.451803
             */
            longitude?: number | null;
            /** @description URL of the venue's official website */
            websiteUrl?: string | null;
            /** @description URL of the venue's logo or photo */
            imageUrl?: string | null;
            /**
             * @description Who to credit for `imageUrl`, worded as the archive publishes it. Present whenever `imageUrl` is, and it must be shown beside the image.
             * @example Photographer Name, via Wikimedia Commons
             */
            imageAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `imageUrl` is published under, or `PD` where no identifier applies. Example values: `CC0-1.0`, `CC-BY-4.0`, `CC-BY-SA-4.0`.
             * @example CC-BY-SA-4.0
             */
            imageLicenceId?: string | null;
            /**
             * @description The image's description page, which the rendered credit links to
             * @example https://commons.wikimedia.org/wiki/File:Example.jpg
             */
            imageSourceUrl?: string | null;
            /** @description Alternative formats of the same image, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
            /** @description Short prose description of the venue */
            description?: string | null;
            /**
             * @description Language of `description`: `de` or `en`. Null when the language is unknown.
             * @example en
             */
            descriptionLanguage?: string | null;
            /**
             * @description The same description in the other language. Written by hand, not machine-translated, so it carries no origin and needs no disclosure (#1210).
             * @example Ein Konzertsaal in Friedrichshain.
             */
            descriptionAlt?: string | null;
            /**
             * @description Language of `descriptionAlt`: `de` or `en`. Null exactly when `descriptionAlt` is.
             * @example de
             */
            descriptionAltLanguage?: string | null;
            /**
             * @description What kind of place this is, as venue type slugs, curated by hand. Empty until curated.
             * @example [
             *       "live-venue",
             *       "club"
             *     ]
             */
            venueTypes?: string[];
            /**
             * Format: int32
             * @description How many visitors the largest room holds, as the venue publishes it. Null where it does not.
             * @example 1500
             */
            capacity?: number | null;
            /**
             * @description Genre family slugs the venue mostly programmes, most frequent first, derived from its events of the last year and ahead.
             * @example [
             *       "rock",
             *       "punk"
             *     ]
             */
            programmeFamilies?: string[];
            /**
             * @description Event types the venue hosts, most frequent first, derived from its events like `programmeFamilies`.
             * @example [
             *       "CONCERT",
             *       "PARTY"
             *     ]
             */
            programmeEventTypes?: string[];
            /** @description What the venue says about itself (its kind of space, its door, its access), as character tag slugs, ordered by slug. Set only where the venue's own page states it. Each carries the URL of the venue's own page that states it. */
            characterTags?: components["schemas"]["VenueCharacterTagResponse"][];
            /**
             * @description Whether we import this venue's events. False for a venue we know but do not import yet: it has no events here, and its page links to its programme.
             * @example false
             */
            imported?: boolean;
            /**
             * @description Where the venue publishes its programme, for a venue whose events we do not import: its own page, else its Resident Advisor page, else a ticket platform. A plain outbound link. Null for an imported venue, and for one with no programme online.
             * @example https://www.example-club.de/programm
             */
            programmeUrl?: string | null;
        };
        /** @description Compact artist summary */
        ArtistSummaryResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 7
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example the-adicts
             */
            slug?: string;
            /**
             * @description Stage name or band name
             * @example The Adicts
             */
            name?: string;
            /** @description URL of the artist's photo or band logo */
            imageUrl?: string | null;
            /**
             * @description Who to credit for `imageUrl`, worded as the archive publishes it. Present whenever `imageUrl` is, and it must be shown beside the image.
             * @example Photographer Name, via Wikimedia Commons
             */
            imageAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `imageUrl` is published under, or `PD` where no identifier applies. Example values: `CC0-1.0`, `CC-BY-4.0`, `CC-BY-SA-4.0`.
             * @example CC-BY-SA-4.0
             */
            imageLicenceId?: string | null;
            /**
             * @description The image's description page, which the rendered credit links to
             * @example https://commons.wikimedia.org/wiki/File:Example.jpg
             */
            imageSourceUrl?: string | null;
            /** @description Alternative formats of the same image, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
            /** @description URL of the artist's Bandcamp page, which the event page's lineup links to */
            bandcampUrl?: string | null;
            /** @description URL of the artist's SoundCloud profile, which the event page's lineup links to */
            soundcloudUrl?: string | null;
        };
        /** @description Compact event summary for lists and calendar */
        EventSummaryResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 101
             */
            id?: number;
            /**
             * @description URL-friendly identifier (format: {date}-{venue}-{title})
             * @example 2026-06-18-lido-sam-prekop-john-mcentire
             */
            slug?: string;
            /**
             * @description Main headline or name of the event
             * @example THE ADICTS
             */
            title?: string;
            /** @description Secondary line, often a tour name or support acts */
            subtitle?: string | null;
            /**
             * @description Kind of event
             * @example CONCERT
             * @enum {string}
             */
            eventType?: "CONCERT" | "FESTIVAL" | "PARTY" | "QUIZ" | "SHOW" | "COMEDY" | "SCREENING" | "EXHIBITION" | "READING" | "OTHER";
            /**
             * @description Scheduling status of the event
             * @example SCHEDULED
             * @enum {string}
             */
            status?: "SCHEDULED" | "RELOCATED" | "CANCELLED" | "POSTPONED";
            /**
             * @description Where a RELOCATED event moved to, as the venue's own note names the house; absent on every other status
             * @example Hole44
             */
            relocatedTo?: string | null;
            /**
             * @description What is said on stage or on screen, as ISO 639-1 codes, where the venue states it. Absent means unknown, never German by default. Not the language of the description.
             * @example [
             *       "en"
             *     ]
             */
            spokenLanguages?: string[] | null;
            /**
             * @description The subtitles of a screening shown in the original, as an ISO 639-1 code: `de` for OmU
             * @example de
             */
            subtitleLanguage?: string | null;
            /**
             * Format: date
             * @description Calendar date of the event
             * @example 2026-06-12
             */
            eventDate?: string;
            /**
             * Format: time-local
             * @description Time when doors open to the public
             * @example 19:00
             */
            doorsTime?: string | null;
            /**
             * Format: time-local
             * @description Time when the show/performance starts
             * @example 20:00
             */
            startTime?: string | null;
            /**
             * Format: date
             * @description Last day of the event, only when the venue stated one; null means it ends on `eventDate`. A weekender carries the Monday here, a run of weeks its closing day.
             * @example 2026-06-15
             */
            endDate?: string | null;
            /**
             * Format: time-local
             * @description Time the event ends on `endDate`, only when the venue stated one. Never set without `endDate`.
             * @example 10:00
             */
            endTime?: string | null;
            /**
             * Format: time-local
             * @description Our guess at the start, from the kind of event, when the venue published neither `startTime` nor `doorsTime`; null whenever either is set. The list sorts by it, and a page must show it as a guess.
             * @example 23:00
             */
            assumedStartTime?: string | null;
            /** @description Where the poster is fetched from. A path on this origin once the environment serves cached images, and the venue's own URL until then (ADR-019). */
            imageUrl?: string | null;
            /** @description Better formats of the same poster, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
            /**
             * @description True when a licence prohibition removed the image. False both when the venue published none and when one is shown — a placeholder renders either way.
             * @example false
             */
            imageWithheld?: boolean;
            /**
             * @description Presale ticket price (Vorverkauf)
             * @example 38
             */
            pricePresale?: number | null;
            /**
             * @description Box office ticket price (Abendkasse)
             * @example 45
             */
            priceBoxOffice?: number | null;
            /**
             * @description ISO 4217 currency code for prices
             * @example EUR
             */
            priceCurrency?: string;
            /** @description Free-form pricing note for non-standard pricing */
            priceNote?: string | null;
            /**
             * @description Whether all tickets for this event are sold out
             * @example false
             */
            soldOut?: boolean;
            /**
             * @description Whether the event is free to attend (free entry)
             * @example false
             */
            free?: boolean;
            /** @description The venue where this event takes place */
            venue?: components["schemas"]["VenueSummaryResponse"];
            /**
             * @description Artist names in billing order (headliner first)
             * @example [
             *       "The Adicts",
             *       "Maid Of Ace"
             *     ]
             */
            artistNames?: string[];
            /**
             * @description Normalized genre tags
             * @example [
             *       "Punk"
             *     ]
             */
            genreTags?: string[];
        };
        /** @description Promoter list row */
        PromoterListItemResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 3
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example 36-concerts
             */
            slug?: string;
            /**
             * @description Display name of the promoter
             * @example 36 Concerts
             */
            name?: string;
            /** @description URL of the promoter's website or social page */
            websiteUrl?: string | null;
            /** @description Short prose description of the promoter */
            description?: string | null;
            /**
             * @description Language of `description`: `de` or `en`. Null when the language is unknown.
             * @example en
             */
            descriptionLanguage?: string | null;
            /** @description The same description in the other language, written by hand (#328). */
            descriptionAlt?: string | null;
            /**
             * @description Language of `descriptionAlt`: `de` or `en`. Null exactly when `descriptionAlt` is.
             * @example de
             */
            descriptionAltLanguage?: string | null;
            /**
             * Format: int32
             * @description Events from today on that credit this promoter
             * @example 220
             */
            upcomingEventCount?: number;
            /**
             * Format: int32
             * @description Events crediting this promoter that start within the next 30 days, Berlin time. The list's `upcomingEvents` sort orders by this count.
             * @example 12
             */
            upcomingNext30DaysCount?: number;
        };
        /** @description The first matches of one kind, and how many there are in all */
        SearchGroupArtistSummaryResponse: {
            /** @description At most `limit` items */
            items?: components["schemas"]["ArtistSummaryResponse"][];
            /**
             * Format: int64
             * @description Total number of matches of this kind, at most 100
             * @example 12
             */
            total?: number;
            /** @description True when there are more than `total` matches */
            totalCapped?: boolean;
        };
        /** @description The first matches of one kind, and how many there are in all */
        SearchGroupEventSummaryResponse: {
            /** @description At most `limit` items */
            items?: components["schemas"]["EventSummaryResponse"][];
            /**
             * Format: int64
             * @description Total number of matches of this kind, at most 100
             * @example 12
             */
            total?: number;
            /** @description True when there are more than `total` matches */
            totalCapped?: boolean;
        };
        /** @description The first matches of one kind, and how many there are in all */
        SearchGroupPromoterListItemResponse: {
            /** @description At most `limit` items */
            items?: components["schemas"]["PromoterListItemResponse"][];
            /**
             * Format: int64
             * @description Total number of matches of this kind, at most 100
             * @example 12
             */
            total?: number;
            /** @description True when there are more than `total` matches */
            totalCapped?: boolean;
        };
        /** @description The first matches of one kind, and how many there are in all */
        SearchGroupVenueListItemResponse: {
            /** @description At most `limit` items */
            items?: components["schemas"]["VenueListItemResponse"][];
            /**
             * Format: int64
             * @description Total number of matches of this kind, at most 100
             * @example 12
             */
            total?: number;
            /** @description True when there are more than `total` matches */
            totalCapped?: boolean;
        };
        /** @description The first matches of each kind, for the header search */
        SearchResponse: {
            /** @description Upcoming events, by date */
            events?: components["schemas"]["SearchGroupEventSummaryResponse"];
            /** @description Venues, best match first */
            venues?: components["schemas"]["SearchGroupVenueListItemResponse"];
            /** @description Artists, best match first */
            artists?: components["schemas"]["SearchGroupArtistSummaryResponse"];
            /** @description Promoters, best match first */
            promoters?: components["schemas"]["SearchGroupPromoterListItemResponse"];
            /** @description Events that are over, latest first. Empty unless the request says `past=true` */
            past?: components["schemas"]["SearchGroupEventSummaryResponse"];
        };
        /** @description Compact venue summary */
        VenueSummaryResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 42
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example astra-kulturhaus
             */
            slug?: string;
            /**
             * @description Display name of the venue
             * @example Astra Kulturhaus
             */
            name?: string;
            /**
             * @description City where the venue is located
             * @example Berlin
             */
            city?: string;
            /**
             * @description Street address of the venue
             * @example Revaler Str. 99
             */
            address?: string | null;
            /**
             * @description Berlin district (one of the 23 pre-2001 Bezirke) as a canonical slug
             * @example kreuzberg
             */
            district?: string | null;
            /**
             * @description Geographic latitude for map display
             * @example 52.507242
             */
            latitude?: number | null;
            /**
             * @description Geographic longitude for map display
             * @example 13.451803
             */
            longitude?: number | null;
            /** @description URL of the venue's logo or photo */
            imageUrl?: string | null;
            /**
             * @description Who to credit for `imageUrl`, worded as the archive publishes it. Present whenever `imageUrl` is, and it must be shown beside the image.
             * @example Photographer Name, via Wikimedia Commons
             */
            imageAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `imageUrl` is published under, or `PD` where no identifier applies. Example values: `CC0-1.0`, `CC-BY-4.0`, `CC-BY-SA-4.0`.
             * @example CC-BY-SA-4.0
             */
            imageLicenceId?: string | null;
            /**
             * @description The image's description page, which the rendered credit links to
             * @example https://commons.wikimedia.org/wiki/File:Example.jpg
             */
            imageSourceUrl?: string | null;
            /** @description Alternative formats of the same image, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
        };
        /** @description A page of results with pagination metadata */
        PageResponsePromoterListItemResponse: {
            /** @description The items on this page */
            content?: components["schemas"]["PromoterListItemResponse"][];
            /**
             * Format: int32
             * @description Zero-based index of this page
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 20
             */
            size?: number;
            /**
             * Format: int64
             * @description Total number of matching items across all pages
             * @example 137
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description Total number of pages
             * @example 7
             */
            totalPages?: number;
        };
        /** @description Full promoter detail */
        PromoterDetailResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 3
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example 36-concerts
             */
            slug?: string;
            /**
             * @description Display name of the promoter
             * @example 36 Concerts
             */
            name?: string;
            /** @description URL of the promoter's website or social page */
            websiteUrl?: string | null;
            /** @description URL of the promoter's logo image */
            imageUrl?: string | null;
            /**
             * @description Who to credit for `imageUrl`, worded as the archive publishes it. Present whenever `imageUrl` is, and it must be shown beside the image.
             * @example Photographer Name, via Wikimedia Commons
             */
            imageAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `imageUrl` is published under, or `PD` where no identifier applies. Example values: `CC0-1.0`, `CC-BY-4.0`, `CC-BY-SA-4.0`.
             * @example CC-BY-SA-4.0
             */
            imageLicenceId?: string | null;
            /**
             * @description The image's description page, which the rendered credit links to
             * @example https://commons.wikimedia.org/wiki/File:Example.jpg
             */
            imageSourceUrl?: string | null;
            /** @description Alternative formats of the same image, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
            /** @description Short prose description of the promoter */
            description?: string | null;
            /**
             * @description Language of `description`: `de` or `en`. Null when the language is unknown.
             * @example en
             */
            descriptionLanguage?: string | null;
            /**
             * @description The same description in the other language. Written by hand, not machine-translated, so it carries no origin and needs no disclosure (#328).
             * @example Die Hausagentur von Lido, Astra und Bi Nuu.
             */
            descriptionAlt?: string | null;
            /**
             * @description Language of `descriptionAlt`: `de` or `en`. Null exactly when `descriptionAlt` is.
             * @example de
             */
            descriptionAltLanguage?: string | null;
        };
        /** @description Version and commit of the running backend, for the frontend footer */
        MetaResponse: {
            /**
             * @description Application version. `dev` when the build did not stamp one — i.e. running from the IDE or `bootRun`.
             * @example 0.1.0
             */
            version?: string;
            /**
             * @description Full commit SHA the running artifact was built from; null when unavailable.
             * @example 9f1a2b3c4d5e6f708192a3b4c5d6e7f809a1b2c3
             */
            commit?: string | null;
            /**
             * @description First seven characters of `commit`, for display; null when the commit is unavailable.
             * @example 9f1a2b3
             */
            commitShort?: string | null;
            /**
             * @description When the running artifact was built (ISO-8601); null when the build did not stamp one.
             * @example 2026-08-07T12:49:19Z
             */
            buildTime?: string | null;
        };
        /** @description A normalized genre tag */
        GenreTagResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 1
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example hip-hop
             */
            slug?: string;
            /**
             * @description Canonical display name
             * @example Hip Hop
             */
            name?: string;
            /**
             * @description Slug of the filter family the tag belongs to; null means the tag is offered in neither select
             * @example hip-hop
             */
            family?: string | null;
        };
        /** @description A page of results with pagination metadata */
        PageResponseEventSummaryResponse: {
            /** @description The items on this page */
            content?: components["schemas"]["EventSummaryResponse"][];
            /**
             * Format: int32
             * @description Zero-based index of this page
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 20
             */
            size?: number;
            /**
             * Format: int64
             * @description Total number of matching items across all pages
             * @example 137
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description Total number of pages
             * @example 7
             */
            totalPages?: number;
        };
        /** @description Full event detail with embedded associations */
        EventDetailResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 101
             */
            id?: number;
            /**
             * @description URL-friendly identifier (format: {date}-{venue}-{title})
             * @example 2026-06-18-lido-sam-prekop-john-mcentire
             */
            slug?: string;
            /**
             * @description Main headline or name of the event
             * @example THE ADICTS
             */
            title?: string;
            /** @description Secondary line, often a tour name or support acts */
            subtitle?: string | null;
            /** @description Longer description or artist biography */
            description?: string | null;
            /**
             * @description Language of `description` as detected at import: `de` or `en`. Null when the text is too short or holds both languages, in which case the page claims no language for it (ADR-026).
             * @example de
             */
            descriptionLanguage?: string | null;
            /** @description The description in the other locale, when there is one. Written by the publisher, or by a machine where the source's grant allows it. Null far more often than not. */
            descriptionAlt?: string | null;
            /**
             * @description Language of `descriptionAlt`: `de` or `en`. Null exactly when `descriptionAlt` is.
             * @example en
             */
            descriptionAltLanguage?: string | null;
            /**
             * @description Who wrote `descriptionAlt`: `PUBLISHER` or `MACHINE`. A machine translation is labelled as such on the page and links to the source. Null exactly when `descriptionAlt` is.
             * @example PUBLISHER
             */
            descriptionAltOrigin?: string | null;
            /**
             * @description Kind of event
             * @example CONCERT
             * @enum {string}
             */
            eventType?: "CONCERT" | "FESTIVAL" | "PARTY" | "QUIZ" | "SHOW" | "COMEDY" | "SCREENING" | "EXHIBITION" | "READING" | "OTHER";
            /**
             * @description Scheduling status of the event
             * @example SCHEDULED
             * @enum {string}
             */
            status?: "SCHEDULED" | "RELOCATED" | "CANCELLED" | "POSTPONED";
            /**
             * @description Where a RELOCATED event moved to, as the venue's own note names the house; absent on every other status
             * @example Hole44
             */
            relocatedTo?: string | null;
            /**
             * @description What is said on stage or on screen, as ISO 639-1 codes, where the venue states it. Absent means unknown, never German by default. Not the language of the description.
             * @example [
             *       "en"
             *     ]
             */
            spokenLanguages?: string[] | null;
            /**
             * @description The subtitles of a screening shown in the original, as an ISO 639-1 code: `de` for OmU
             * @example de
             */
            subtitleLanguage?: string | null;
            /**
             * Format: date
             * @description Calendar date of the event
             * @example 2026-06-12
             */
            eventDate?: string;
            /**
             * Format: time-local
             * @description Time when doors open to the public
             * @example 19:00
             */
            doorsTime?: string | null;
            /**
             * Format: time-local
             * @description Time when the show/performance starts
             * @example 20:00
             */
            startTime?: string | null;
            /**
             * Format: date
             * @description Last day of the event, only when the venue stated one; null means it ends on `eventDate`. A weekender carries the Monday here, a run of weeks its closing day.
             * @example 2026-06-15
             */
            endDate?: string | null;
            /**
             * Format: time-local
             * @description Time the event ends on `endDate`, only when the venue stated one. Never set without `endDate`.
             * @example 10:00
             */
            endTime?: string | null;
            /**
             * Format: time-local
             * @description Our guess at the start, from the kind of event, when the venue published neither `startTime` nor `doorsTime`; null whenever either is set. The list sorts by it, and a page must show it as a guess.
             * @example 23:00
             */
            assumedStartTime?: string | null;
            /** @description Where the poster is fetched from. A path on this origin once the environment serves cached images, and the venue's own URL until then (ADR-019). */
            imageUrl?: string | null;
            /** @description Better formats of the same poster, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
            /**
             * @description True when a licence prohibition removed the image. False both when the venue published none and when one is shown — a placeholder renders either way.
             * @example false
             */
            imageWithheld?: boolean;
            /**
             * @description True when a licence prohibition removed the description. False when the venue simply wrote none, which is far more common and needs no explanation.
             * @example false
             */
            descriptionWithheld?: boolean;
            /** @description Original URL on the source venue's website */
            sourceUrl?: string | null;
            /**
             * @description The page the lineup was taken from when it is not `sourceUrl`, such as a fan-run timetable. The page must credit it beside the lineup (ADR-036). Null for almost every event.
             * @example https://sisy.fan/events/from/25.09.2026/to/28.09.2026
             */
            lineupSourceUrl?: string | null;
            /** @description URL to the external ticket shop */
            ticketUrl?: string | null;
            /** @description Direct link to the Facebook event page */
            facebookEventUrl?: string | null;
            /**
             * @description Music genre or style tag (raw text from source)
             * @example Punk
             */
            genre?: string | null;
            /**
             * @description Presale ticket price (Vorverkauf)
             * @example 38
             */
            pricePresale?: number | null;
            /**
             * @description Box office ticket price (Abendkasse)
             * @example 45
             */
            priceBoxOffice?: number | null;
            /**
             * @description ISO 4217 currency code for prices
             * @example EUR
             */
            priceCurrency?: string;
            /** @description Free-form pricing note for non-standard pricing */
            priceNote?: string | null;
            /**
             * @description Whether all tickets for this event are sold out
             * @example false
             */
            soldOut?: boolean;
            /**
             * @description Whether the event is free to attend (free entry)
             * @example false
             */
            free?: boolean;
            /** @description The venue where this event takes place */
            venue?: components["schemas"]["VenueSummaryResponse"];
            /**
             * @description The room of the venue the whole event is in, as the venue names it. Null when the venue names none, and on a lineup split across rooms, where each entry's `stage` says it instead.
             * @example Saal
             */
            room?: string | null;
            /** @description Lineup in billing order (headliner first) */
            lineup?: components["schemas"]["LineupEntryResponse"][];
            /** @description Promoters or presenters responsible for this event */
            promoters?: components["schemas"]["PromoterSummaryResponse"][];
            /**
             * @description Normalized genre tags
             * @example [
             *       "Punk"
             *     ]
             */
            genreTags?: string[];
        };
        /** @description An artist's participation in an event lineup */
        LineupEntryResponse: {
            /** @description The performing artist */
            artist?: components["schemas"]["ArtistSummaryResponse"];
            /**
             * @description The artist's role in the lineup
             * @example HEADLINER
             * @enum {string}
             */
            role?: "HEADLINER" | "SUPPORT" | "DJ";
            /**
             * Format: int32
             * @description Position in the lineup — lower numbers appear first
             * @example 0
             */
            billingOrder?: number;
            /**
             * @description The room or floor the act plays when the lineup is split across rooms, or null
             * @example Panorama Bar
             */
            stage?: string | null;
            /**
             * Format: date-time
             * @description Start of the set in Berlin time, from the venue's running order, or null
             * @example 2026-09-26T23:59:00+02:00
             */
            setStart?: string | null;
            /**
             * Format: date-time
             * @description End of the set in Berlin time, or null
             * @example 2026-09-27T04:30:00+02:00
             */
            setEnd?: string | null;
        };
        /** @description Compact promoter summary */
        PromoterSummaryResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 3
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example 36-concerts
             */
            slug?: string;
            /**
             * @description Display name of the promoter
             * @example 36 Concerts
             */
            name?: string;
            /** @description URL of the promoter's website or social page */
            websiteUrl?: string | null;
            /** @description URL of the promoter's logo image */
            imageUrl?: string | null;
            /**
             * @description Who to credit for `imageUrl`, worded as the archive publishes it. Present whenever `imageUrl` is, and it must be shown beside the image.
             * @example Photographer Name, via Wikimedia Commons
             */
            imageAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `imageUrl` is published under, or `PD` where no identifier applies. Example values: `CC0-1.0`, `CC-BY-4.0`, `CC-BY-SA-4.0`.
             * @example CC-BY-SA-4.0
             */
            imageLicenceId?: string | null;
            /**
             * @description The image's description page, which the rendered credit links to
             * @example https://commons.wikimedia.org/wiki/File:Example.jpg
             */
            imageSourceUrl?: string | null;
            /** @description Alternative formats of the same image, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
        };
        /** @description A page of results with pagination metadata */
        PageResponseArtistSummaryResponse: {
            /** @description The items on this page */
            content?: components["schemas"]["ArtistSummaryResponse"][];
            /**
             * Format: int32
             * @description Zero-based index of this page
             * @example 0
             */
            page?: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 20
             */
            size?: number;
            /**
             * Format: int64
             * @description Total number of matching items across all pages
             * @example 137
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description Total number of pages
             * @example 7
             */
            totalPages?: number;
        };
        /** @description Full artist detail */
        ArtistDetailResponse: {
            /**
             * Format: int64
             * @description Database primary key
             * @example 7
             */
            id?: number;
            /**
             * @description URL-friendly identifier
             * @example the-adicts
             */
            slug?: string;
            /**
             * @description Stage name or band name
             * @example The Adicts
             */
            name?: string;
            /** @description Biography or description text */
            description?: string | null;
            /**
             * @description Language of `description`: `de` or `en`. Null when the language is unknown.
             * @example en
             */
            descriptionLanguage?: string | null;
            /**
             * @description Who to credit for `description` when it is licensed text. Null for a text a venue or a person wrote; set exactly when `descriptionLicenceId` and `descriptionSourceUrl` are
             * @example Wikipedia
             */
            descriptionAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `description` is published under
             * @example CC-BY-SA-4.0
             */
            descriptionLicenceId?: string | null;
            /**
             * @description The page `description` was taken from, which the rendered credit links to
             * @example https://en.wikipedia.org/wiki/Buffalo_Tom
             */
            descriptionSourceUrl?: string | null;
            /**
             * @description The other Wikipedia's own lead beside a Wikipedia `description`, in the other language. Null beside a text a venue or a person wrote
             * @example Buffalo Tom ist eine US-amerikanische Alternative-Rock-Band aus Boston.
             */
            descriptionAlt?: string | null;
            /**
             * @description Language of `descriptionAlt`: `de` or `en`. Null exactly when `descriptionAlt` is.
             * @example de
             */
            descriptionAltLanguage?: string | null;
            /**
             * @description Who to credit for `descriptionAlt`. Set exactly when `descriptionAlt` is
             * @example Wikipedia
             */
            descriptionAltAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `descriptionAlt` is published under
             * @example CC-BY-SA-4.0
             */
            descriptionAltLicenceId?: string | null;
            /**
             * @description The page `descriptionAlt` was taken from, which the rendered credit links to
             * @example https://de.wikipedia.org/wiki/Buffalo_Tom
             */
            descriptionAltSourceUrl?: string | null;
            /** @description URL of the artist's photo or band logo */
            imageUrl?: string | null;
            /**
             * @description Who to credit for `imageUrl`, worded as the archive publishes it. Present whenever `imageUrl` is, and it must be shown beside the image.
             * @example Photographer Name, via Wikimedia Commons
             */
            imageAttribution?: string | null;
            /**
             * @description SPDX identifier of the licence `imageUrl` is published under, or `PD` where no identifier applies. Example values: `CC0-1.0`, `CC-BY-4.0`, `CC-BY-SA-4.0`.
             * @example CC-BY-SA-4.0
             */
            imageLicenceId?: string | null;
            /**
             * @description The image's description page, which the rendered credit links to
             * @example https://commons.wikimedia.org/wiki/File:Example.jpg
             */
            imageSourceUrl?: string | null;
            /** @description Alternative formats of the same image, best first, for a <picture> element. Empty when the image is not cached, in which case `imageUrl` is all there is. */
            imageSources?: components["schemas"]["ImageSourceResponse"][];
            /**
             * Format: int32
             * @description Pixel width of the original image, for the `width` attribute. Null together with `intrinsicHeight` when the dimensions are unknown.
             * @example 1200
             */
            intrinsicWidth?: number | null;
            /**
             * Format: int32
             * @description Pixel height of the original image, for the `height` attribute
             * @example 630
             */
            intrinsicHeight?: number | null;
            /** @description URL of the artist's official homepage */
            websiteUrl?: string | null;
            /** @description URL of the artist's Facebook page */
            facebookUrl?: string | null;
            /** @description URL of the artist's Instagram profile */
            instagramUrl?: string | null;
            /** @description URL of the artist's YouTube channel */
            youtubeUrl?: string | null;
            /** @description URL of the artist's Bandcamp page */
            bandcampUrl?: string | null;
            /** @description URL of the artist's SoundCloud profile */
            soundcloudUrl?: string | null;
            /** @description URL of the artist's Discogs page */
            discogsUrl?: string | null;
            /** @description URL of the artist's Resident Advisor page */
            residentAdvisorUrl?: string | null;
            /** @description URL of the artist's Spotify page */
            spotifyUrl?: string | null;
            /**
             * @description The artist's MusicBrainz page, the correction path for a wrong match; set exactly when `musicbrainzMatch` is `EXACT`
             * @example https://musicbrainz.org/artist/41f4d85a-0bd7-4602-a3e3-8c47f36efb0a
             */
            musicbrainzUrl?: string | null;
            /**
             * @description What kind of act this is, as MusicBrainz types it; null until read
             * @example GROUP
             * @enum {string|null}
             */
            artistType?: "PERSON" | "GROUP" | "ORCHESTRA" | "CHOIR" | "OTHER" | null;
            /**
             * @description MusicBrainz artist id (MBID), set exactly when `musicbrainzMatch` is `EXACT`
             * @example 41f4d85a-0bd7-4602-a3e3-8c47f36efb0a
             */
            musicbrainzId?: string | null;
            /**
             * @description What the MusicBrainz lookup decided about the name (ADR-031)
             * @example EXACT
             * @enum {string}
             */
            musicbrainzMatch?: "EXACT" | "AMBIGUOUS" | "NONE" | "UNCHECKED";
            /**
             * Format: date-time
             * @description When that verdict was reached
             */
            musicbrainzCheckedAt?: string | null;
            /**
             * @description What the Discogs lookup decided about a name MusicBrainz does not know (#2026); `EXACT` means Discogs gave `discogsUrl`
             * @example EXACT
             * @enum {string}
             */
            discogsMatch?: "EXACT" | "AMBIGUOUS" | "NONE" | "UNCHECKED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                /** @description Search on the venue name: ignores case, accents and spaces, and forgives small typos. Omitted/blank returns all venues. */
                q?: string;
                /** @description District filter, one of the 23 pre-2001 Berlin districts (e.g. kreuzberg). Repeatable: a venue in any given district matches. */
                district?: string[];
                /** @description Venue type slug (e.g. club). Repeatable: a venue of any given type matches. An unknown type matches nothing. */
                type?: string[];
                /** @description Genre family slug (e.g. electronic). Repeatable: a venue that mostly programmes any given family matches. */
                family?: string[];
                /** @description Event type, e.g. CONCERT (case-insensitive). Repeatable: a venue that hosts any given type matches. */
                eventType?: string[];
                /** @description Character tag slug (e.g. queer), as the venue describes itself. Repeatable: only a venue with every given tag matches. An unknown tag matches nothing. */
                character?: string[];
                /** @description true lists only the venues whose events we import, false only those we know but do not import yet. Omitted lists both. */
                imported?: boolean;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseVenueListItemResponse"];
                };
            };
        };
    };
    findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique venue slug.
                 * @example lido
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueDetailResponse"];
                };
            };
        };
    };
    featureCounts: {
        parameters: {
            query?: {
                /** @description Search on the venue name: ignores case, accents and spaces, and forgives small typos. Omitted/blank returns all venues. */
                q?: string;
                /** @description District filter, one of the 23 pre-2001 Berlin districts (e.g. kreuzberg). Repeatable: a venue in any given district matches. */
                district?: string[];
                /** @description Venue type slug (e.g. club). Repeatable: a venue of any given type matches. An unknown type matches nothing. */
                type?: string[];
                /** @description Genre family slug (e.g. electronic). Repeatable: a venue that mostly programmes any given family matches. */
                family?: string[];
                /** @description Event type, e.g. CONCERT (case-insensitive). Repeatable: a venue that hosts any given type matches. */
                eventType?: string[];
                /** @description Character tag slug (e.g. queer), as the venue describes itself. Repeatable: only a venue with every given tag matches. An unknown tag matches nothing. */
                character?: string[];
                /** @description true lists only the venues whose events we import, false only those we know but do not import yet. Omitted lists both. */
                imported?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    sitemap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search term, at least 2 characters: ignores case, accents and spaces, and forgives small typos. */
                q: string;
                /**
                 * @description Most items per kind, 1 to 20.
                 * @example 5
                 */
                limit?: number;
                /** @description Also return the events that are over, in `past`. Leave it out for type-ahead: it is one more query. */
                past?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                /** @description Search on the promoter name: ignores case, accents and spaces, and forgives small typos. Omitted/blank returns all promoters. */
                q?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponsePromoterListItemResponse"];
                };
            };
        };
    };
    findBySlug_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique promoter slug.
                 * @example 36-concerts
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PromoterDetailResponse"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    serve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SHA-256 of the original bytes, lower-case hex. */
                contentHash: string;
                /**
                 * @description Width and format, as `<width>.<format>`.
                 * @example 768.jpg
                 */
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenreTagResponse"][];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                /** @description Earliest event date (inclusive), ISO-8601 (e.g. 2026-06-19). Defaults to today when both from/to are omitted. */
                from?: string;
                /** @description Latest event date (inclusive), ISO-8601 (e.g. 2026-06-30). */
                to?: string;
                /** @description When true, 'from' keeps every event still running on that day: one that ends on or after 'from' and starts on or before 'to'. Without it, 'from' is the earliest start date. Defaults to false. */
                running?: boolean;
                /** @description Event type filter, e.g. CONCERT (case-insensitive). Repeatable: an event of any given type matches. An unknown type matches nothing. */
                eventType?: string[];
                /** @description Venue slug filter — only events at the matching venue. */
                venue?: string;
                /** @description Pre-2001 Berlin district slug (e.g. kreuzberg). Repeatable: an event at a venue in any given district matches. */
                district?: string[];
                /** @description Venue type slug (e.g. club). Repeatable: an event at a venue of any given type matches. An unknown type matches nothing. */
                venueType?: string[];
                /** @description Artist slug filter — only events featuring the matching artist. */
                artist?: string;
                /** @description Promoter slug filter — only events from the matching promoter. */
                promoter?: string;
                /** @description Genre tag slug filter — only events tagged with the matching genre. */
                genre?: string;
                /** @description Genre family slug filter (e.g. electronic). Repeatable: an event tagged with a genre in any given family matches. */
                family?: string[];
                /** @description Minimum presale price (inclusive). Excludes events with an unknown (null) price. */
                minPrice?: number;
                /** @description Maximum presale price (inclusive). Excludes events with an unknown (null) price. */
                maxPrice?: number;
                /** @description Search over the event title, subtitle, venue name, lineup and promoters: ignores case, accents and spaces, and forgives small typos. */
                q?: string;
                /** @description When true, excludes events flagged as sold out. Defaults to false (include all). */
                excludeSoldOut?: boolean;
                /** @description When true, returns only events flagged as free to attend. Defaults to false. */
                free?: boolean;
                /** @description Time of night, Berlin time: daytime (06:00-17:59), evening (18:00-21:59) or late (22:00-05:59). An event with an end matches every slot it runs through, and one of 24 hours or more matches all three; without an end, its start, else its doors time, decides. Repeatable: an event in any given slot matches. An event with neither time is left out. An unknown value matches nothing. */
                timeOfDay?: string[];
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseEventSummaryResponse"];
                };
            };
        };
    };
    findBySlug_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique event slug (format: {date}-{venue}-{title}).
                 * @example 2026-06-18-lido-sam-prekop-john-mcentire
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetailResponse"];
                };
            };
        };
    };
    related: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Slug of the event to match.
                 * @example 2026-06-18-lido-sam-prekop-john-mcentire
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventSummaryResponse"][];
                };
            };
        };
    };
    today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventSummaryResponse"][];
                };
            };
        };
    };
    feed: {
        parameters: {
            query?: {
                /**
                 * @description Language of the feed's text and links: en or de.
                 * @example de
                 */
                locale?: string;
                /** @description Event type filter, e.g. CONCERT (case-insensitive). Repeatable: an event of any given type matches. An unknown type matches nothing. */
                eventType?: string[];
                /** @description Venue slug filter — only events at the matching venue. */
                venue?: string;
                /** @description Pre-2001 Berlin district slug (e.g. kreuzberg). Repeatable: an event at a venue in any given district matches. */
                district?: string[];
                /** @description Venue type slug (e.g. club). Repeatable: an event at a venue of any given type matches. An unknown type matches nothing. */
                venueType?: string[];
                /** @description Artist slug filter — only events featuring the matching artist. */
                artist?: string;
                /** @description Promoter slug filter — only events from the matching promoter. */
                promoter?: string;
                /** @description Genre tag slug filter — only events tagged with the matching genre. */
                genre?: string;
                /** @description Genre family slug filter (e.g. electronic). Repeatable: an event tagged with a genre in any given family matches. */
                family?: string[];
                /** @description Minimum presale price (inclusive). Excludes events with an unknown (null) price. */
                minPrice?: number;
                /** @description Maximum presale price (inclusive). Excludes events with an unknown (null) price. */
                maxPrice?: number;
                /** @description Search over the event title, subtitle, venue name, lineup and promoters: ignores case, accents and spaces, and forgives small typos. */
                q?: string;
                /** @description When true, excludes events flagged as sold out. Defaults to false (include all). */
                excludeSoldOut?: boolean;
                /** @description When true, returns only events flagged as free to attend. Defaults to false. */
                free?: boolean;
                /** @description Time of night, Berlin time: daytime (06:00-17:59), evening (18:00-21:59) or late (22:00-05:59). An event with an end matches every slot it runs through, and one of 24 hours or more matches all three; without an end, its start, else its doors time, decides. Repeatable: an event in any given slot matches. An event with neither time is left out. An unknown value matches nothing. */
                timeOfDay?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rss+xml": string;
                };
            };
        };
    };
    calendar: {
        parameters: {
            query: {
                /** @description Range start date (inclusive), ISO-8601. */
                from: string;
                /** @description Range end date (inclusive), ISO-8601. Must not precede 'from' or exceed 92 days from it. */
                to: string;
                /** @description Event type filter, e.g. CONCERT (case-insensitive). Repeatable: an event of any given type matches. An unknown type matches nothing. */
                eventType?: string[];
                /** @description Venue slug filter — only events at the matching venue. */
                venue?: string;
                /** @description Pre-2001 Berlin district slug (e.g. kreuzberg). Repeatable: an event at a venue in any given district matches. */
                district?: string[];
                /** @description Venue type slug (e.g. club). Repeatable: an event at a venue of any given type matches. An unknown type matches nothing. */
                venueType?: string[];
                /** @description Artist slug filter — only events featuring the matching artist. */
                artist?: string;
                /** @description Promoter slug filter — only events from the matching promoter. */
                promoter?: string;
                /** @description Genre tag slug filter — only events tagged with the matching genre. */
                genre?: string;
                /** @description Genre family slug filter (e.g. electronic). Repeatable: an event tagged with a genre in any given family matches. */
                family?: string[];
                /** @description Minimum presale price (inclusive). Excludes events with an unknown (null) price. */
                minPrice?: number;
                /** @description Maximum presale price (inclusive). Excludes events with an unknown (null) price. */
                maxPrice?: number;
                /** @description Search over the event title, subtitle, venue name, lineup and promoters: ignores case, accents and spaces, and forgives small typos. */
                q?: string;
                /** @description When true, excludes events flagged as sold out. Defaults to false (include all). */
                excludeSoldOut?: boolean;
                /** @description When true, returns only events flagged as free to attend. Defaults to false. */
                free?: boolean;
                /** @description Time of night, Berlin time: daytime (06:00-17:59), evening (18:00-21:59) or late (22:00-05:59). An event with an end matches every slot it runs through, and one of 24 hours or more matches all three; without an end, its start, else its doors time, decides. Repeatable: an event in any given slot matches. An event with neither time is left out. An unknown value matches nothing. */
                timeOfDay?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventSummaryResponse"][];
                };
            };
        };
    };
    calendar_1: {
        parameters: {
            query?: {
                /**
                 * @description Language of the entries' links and notes: en or de.
                 * @example de
                 */
                locale?: string;
                /**
                 * @description The calendar's name after "Event Junkie · ": the filters in words, as the site builds them. Display text only. A name over 120 characters is cut at the last whole label.
                 * @example Jazz · Neukölln
                 */
                name?: string;
                /** @description Event type filter, e.g. CONCERT (case-insensitive). Repeatable: an event of any given type matches. An unknown type matches nothing. */
                eventType?: string[];
                /** @description Venue slug filter — only events at the matching venue. */
                venue?: string;
                /** @description Pre-2001 Berlin district slug (e.g. kreuzberg). Repeatable: an event at a venue in any given district matches. */
                district?: string[];
                /** @description Venue type slug (e.g. club). Repeatable: an event at a venue of any given type matches. An unknown type matches nothing. */
                venueType?: string[];
                /** @description Artist slug filter — only events featuring the matching artist. */
                artist?: string;
                /** @description Promoter slug filter — only events from the matching promoter. */
                promoter?: string;
                /** @description Genre tag slug filter — only events tagged with the matching genre. */
                genre?: string;
                /** @description Genre family slug filter (e.g. electronic). Repeatable: an event tagged with a genre in any given family matches. */
                family?: string[];
                /** @description Minimum presale price (inclusive). Excludes events with an unknown (null) price. */
                minPrice?: number;
                /** @description Maximum presale price (inclusive). Excludes events with an unknown (null) price. */
                maxPrice?: number;
                /** @description Search over the event title, subtitle, venue name, lineup and promoters: ignores case, accents and spaces, and forgives small typos. */
                q?: string;
                /** @description When true, excludes events flagged as sold out. Defaults to false (include all). */
                excludeSoldOut?: boolean;
                /** @description When true, returns only events flagged as free to attend. Defaults to false. */
                free?: boolean;
                /** @description Time of night, Berlin time: daytime (06:00-17:59), evening (18:00-21:59) or late (22:00-05:59). An event with an end matches every slot it runs through, and one of 24 hours or more matches all three; without an end, its start, else its doors time, decides. Repeatable: an event in any given slot matches. An event with neither time is left out. An unknown value matches nothing. */
                timeOfDay?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The calendar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                /** @description Search on the artist name: ignores case, accents and spaces, and forgives small typos. Omitted/blank returns all artists. */
                q?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseArtistSummaryResponse"];
                };
            };
        };
    };
    findBySlug_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique artist slug.
                 * @example actors
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArtistDetailResponse"];
                };
            };
        };
    };
}
