-- Generated by SchemaDumpTest from a database migrated to the newest version. Do not edit by hand.
-- Rewrite with ./gradlew :events-importer:updateSchemaDump.

--
-- Name: events; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA events;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA events;

--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';

--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA events;

--
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';

--
-- Name: search_norm(text); Type: FUNCTION; Schema: events; Owner: -
--

CREATE FUNCTION events.search_norm(input text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
    BEGIN ATOMIC
 SELECT TRIM(BOTH FROM regexp_replace(lower((events.unaccent('events.unaccent'::regdictionary, NORMALIZE(input, NFC)) COLLATE pg_c_utf8)), '[^[:alnum:]]+'::text, ' '::text, 'g'::text)) AS btrim;
END;

--
-- Name: search_text(text); Type: FUNCTION; Schema: events; Owner: -
--

CREATE FUNCTION events.search_text(input text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
    BEGIN ATOMIC
 SELECT
         CASE
             WHEN (folded.plain = folded.german) THEN folded.plain
             ELSE ((folded.plain || ' | '::text) || folded.german)
         END AS "case"
    FROM ( SELECT events.search_norm(search_text.input) AS plain,
             events.search_norm(replace(replace(replace(replace(replace(replace(NORMALIZE(search_text.input, NFC), 'ä'::text, 'ae'::text), 'ö'::text, 'oe'::text), 'ü'::text, 'ue'::text), 'Ä'::text, 'Ae'::text), 'Ö'::text, 'Oe'::text), 'Ü'::text, 'Ue'::text)) AS german) folded;
END;

--
-- Name: artist; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.artist (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    description text,
    image_url text,
    website_url text,
    facebook_url text,
    instagram_url text,
    youtube_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    image_attribution text,
    image_licence_id text,
    image_source_url text,
    musicbrainz_id text,
    musicbrainz_match text DEFAULT 'UNCHECKED'::text NOT NULL,
    musicbrainz_checked_at timestamp with time zone,
    bandcamp_url text,
    soundcloud_url text,
    discogs_url text,
    wikidata_url text,
    resident_advisor_url text,
    spotify_url text,
    artist_type text,
    founded text,
    founded_in text,
    country text,
    musicbrainz_enriched_at timestamp with time zone,
    description_language text,
    description_attribution text,
    description_licence_id text,
    description_source_url text,
    description_alt text,
    description_alt_language text,
    description_alt_attribution text,
    description_alt_licence_id text,
    description_alt_source_url text,
    discogs_id bigint,
    discogs_match text DEFAULT 'UNCHECKED'::text NOT NULL,
    discogs_checked_at timestamp with time zone,
    name_changed_at timestamp with time zone DEFAULT now() NOT NULL,
    name_search text GENERATED ALWAYS AS (events.search_text(name)) STORED,
    comedian boolean,
    CONSTRAINT artist_description_alt_attributed CHECK ((((description_alt_attribution IS NULL) AND (description_alt_licence_id IS NULL) AND (description_alt_source_url IS NULL)) OR ((description_alt IS NOT NULL) AND (description_alt_attribution IS NOT NULL) AND (description_alt_licence_id IS NOT NULL) AND (description_alt_source_url IS NOT NULL)))),
    CONSTRAINT artist_description_alt_beside_wikipedia CHECK (((description_alt IS NULL) OR ((description_attribution IS NOT NULL) AND (description_language IS NOT NULL) AND (description_alt_language <> description_language)))),
    CONSTRAINT artist_description_alt_complete CHECK ((((description_alt IS NULL) AND (description_alt_language IS NULL)) OR ((description_alt IS NOT NULL) AND (description_alt_language IS NOT NULL)))),
    CONSTRAINT artist_description_alt_language_valid CHECK (((description_alt_language IS NULL) OR (description_alt_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT artist_description_attributed CHECK ((((description_attribution IS NULL) AND (description_licence_id IS NULL) AND (description_source_url IS NULL)) OR ((description IS NOT NULL) AND (description_attribution IS NOT NULL) AND (description_licence_id IS NOT NULL) AND (description_source_url IS NOT NULL)))),
    CONSTRAINT artist_description_language_valid CHECK (((description_language IS NULL) OR (description_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT artist_discogs_id_only_when_exact CHECK (((discogs_id IS NULL) OR (discogs_match = 'EXACT'::text))),
    CONSTRAINT artist_discogs_match_check CHECK ((discogs_match = ANY (ARRAY['EXACT'::text, 'AMBIGUOUS'::text, 'NONE'::text, 'UNCHECKED'::text]))),
    CONSTRAINT artist_founded_only_for_ensembles CHECK ((((founded IS NULL) AND (founded_in IS NULL)) OR (artist_type = ANY (ARRAY['GROUP'::text, 'ORCHESTRA'::text, 'CHOIR'::text])))),
    CONSTRAINT artist_image_attributed CHECK (((image_url IS NULL) OR ((image_attribution IS NOT NULL) AND (image_licence_id IS NOT NULL) AND (image_source_url IS NOT NULL)))),
    CONSTRAINT artist_musicbrainz_id_only_when_exact CHECK (((musicbrainz_id IS NULL) OR (musicbrainz_match = 'EXACT'::text))),
    CONSTRAINT artist_musicbrainz_match_check CHECK ((musicbrainz_match = ANY (ARRAY['EXACT'::text, 'AMBIGUOUS'::text, 'NONE'::text, 'UNCHECKED'::text]))),
    CONSTRAINT artist_type_check CHECK (((artist_type IS NULL) OR (artist_type = ANY (ARRAY['PERSON'::text, 'GROUP'::text, 'ORCHESTRA'::text, 'CHOIR'::text, 'OTHER'::text]))))
);

--
-- Name: event; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.event (
    id bigint NOT NULL,
    venue_id bigint NOT NULL,
    event_source_id bigint,
    title text NOT NULL,
    subtitle text,
    description text,
    event_type text DEFAULT 'CONCERT'::text NOT NULL,
    status text DEFAULT 'SCHEDULED'::text NOT NULL,
    slug text NOT NULL,
    event_date date NOT NULL,
    doors_time time without time zone,
    start_time time without time zone,
    image_url text,
    source_url text,
    source_id text CONSTRAINT event_source_id_not_null1 NOT NULL,
    ticket_url text,
    facebook_event_url text,
    genre text,
    price_presale numeric(10,2),
    price_box_office numeric(10,2),
    price_currency text DEFAULT 'EUR'::text NOT NULL,
    price_note text,
    sold_out boolean DEFAULT false NOT NULL,
    free boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    description_language text,
    description_language_confidence numeric(4,3),
    description_alt text,
    description_alt_language text,
    description_alt_origin text,
    description_alt_engine text,
    description_alt_source_hash text,
    end_date date,
    end_time time without time zone,
    relocated_to text,
    description_withheld boolean DEFAULT false NOT NULL,
    image_withheld boolean DEFAULT false NOT NULL,
    lineup_source_url text,
    room text,
    title_search text GENERATED ALWAYS AS (events.search_text(title)) STORED,
    subtitle_search text GENERATED ALWAYS AS (events.search_text(subtitle)) STORED,
    type_is_fallback boolean DEFAULT false NOT NULL,
    spoken_languages text[],
    subtitle_language text,
    pinned_fields text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT event_description_alt_complete CHECK ((((description_alt IS NULL) AND (description_alt_language IS NULL) AND (description_alt_origin IS NULL)) OR ((description_alt IS NOT NULL) AND (description_alt_language IS NOT NULL) AND (description_alt_origin IS NOT NULL)))),
    CONSTRAINT event_description_alt_language_valid CHECK (((description_alt_language IS NULL) OR (description_alt_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT event_description_alt_origin_valid CHECK (((description_alt_origin IS NULL) OR (description_alt_origin = ANY (ARRAY['PUBLISHER'::text, 'MACHINE'::text])))),
    CONSTRAINT event_description_language_valid CHECK (((description_language IS NULL) OR (description_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT event_end_after_start CHECK (((end_date IS NULL) OR (end_date >= event_date))),
    CONSTRAINT event_end_time_has_date CHECK (((end_time IS NULL) OR (end_date IS NOT NULL))),
    CONSTRAINT event_spoken_languages_valid CHECK (((spoken_languages IS NULL) OR ((cardinality(spoken_languages) > 0) AND (spoken_languages <@ ARRAY['de'::text, 'en'::text, 'fr'::text, 'es'::text, 'it'::text, 'tr'::text, 'ru'::text, 'pl'::text])))),
    CONSTRAINT event_subtitle_language_valid CHECK (((subtitle_language IS NULL) OR (subtitle_language = ANY (ARRAY['de'::text, 'en'::text, 'fr'::text, 'es'::text, 'it'::text, 'tr'::text, 'ru'::text, 'pl'::text]))))
);

--
-- Name: event_artist; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.event_artist (
    id bigint NOT NULL,
    event_id bigint NOT NULL,
    artist_id bigint NOT NULL,
    role text DEFAULT 'HEADLINER'::text NOT NULL,
    billing_order integer DEFAULT 0 NOT NULL,
    stage text,
    title_derived boolean DEFAULT false NOT NULL,
    set_start timestamp with time zone,
    set_end timestamp with time zone
);

--
-- Name: drop_artist_billed_only_by(text, text); Type: FUNCTION; Schema: events; Owner: -
--

CREATE FUNCTION events.drop_artist_billed_only_by(artist_slug text, source_prefix text) RETURNS integer
    LANGUAGE sql STRICT
    BEGIN ATOMIC
 WITH dropped AS (
          DELETE FROM events.artist a
           WHERE ((a.slug = drop_artist_billed_only_by.artist_slug) AND (NOT (EXISTS ( SELECT 1
                    FROM (events.event_artist ea
                      JOIN events.event e ON ((e.id = ea.event_id)))
                   WHERE ((ea.artist_id = a.id) AND (NOT starts_with(e.source_id, drop_artist_billed_only_by.source_prefix)))))))
           RETURNING 1 AS "?column?"
         )
  SELECT (count(*))::integer AS count
    FROM dropped;
END;

--
-- Name: set_name_changed_at(); Type: FUNCTION; Schema: events; Owner: -
--

CREATE FUNCTION events.set_name_changed_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.name_changed_at = now();
    RETURN NEW;
END;
$$;

--
-- Name: set_updated_at(); Type: FUNCTION; Schema: events; Owner: -
--

CREATE FUNCTION events.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

--
-- Name: artist_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.artist ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.artist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: cached_image; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.cached_image (
    id bigint NOT NULL,
    source_url text NOT NULL,
    content_hash text,
    content_type text,
    byte_size bigint,
    intrinsic_width integer,
    intrinsic_height integer,
    etag text,
    last_modified text,
    fetched_at timestamp with time zone,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    failed_at timestamp with time zone,
    failure_reason text,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: cached_image_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.cached_image ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.cached_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: cached_image_variant; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.cached_image_variant (
    id bigint NOT NULL,
    cached_image_id bigint NOT NULL,
    width integer NOT NULL,
    format text NOT NULL,
    storage_key text NOT NULL,
    byte_size bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: cached_image_variant_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.cached_image_variant ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.cached_image_variant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: data_quality_snapshot; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.data_quality_snapshot (
    id bigint NOT NULL,
    snapshot_date date NOT NULL,
    source_slug text NOT NULL,
    metric text NOT NULL,
    metric_count bigint NOT NULL,
    total_events bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: data_quality_snapshot_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.data_quality_snapshot ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.data_quality_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: event_artist_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.event_artist ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.event_artist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: event_genre_tag; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.event_genre_tag (
    id bigint NOT NULL,
    event_id bigint NOT NULL,
    genre_tag_id bigint NOT NULL
);

--
-- Name: event_genre_tag_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.event_genre_tag ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.event_genre_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: event_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.event ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: event_promoter; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.event_promoter (
    id bigint NOT NULL,
    event_id bigint NOT NULL,
    promoter_id bigint NOT NULL
);

--
-- Name: event_promoter_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.event_promoter ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.event_promoter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: event_source; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.event_source (
    id bigint NOT NULL,
    venue_id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    source_type text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    import_interval_minutes integer DEFAULT 1440 NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retries integer DEFAULT 3 NOT NULL,
    etag text,
    last_modified text,
    last_import_at timestamp with time zone,
    last_event_count integer,
    last_error text,
    status text DEFAULT 'IDLE'::text NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_success_at timestamp with time zone,
    flagged_at timestamp with time zone,
    flag_reason text,
    robots_checked_at timestamp with time zone,
    robots_allowed boolean,
    robots_txt_url text,
    description_licence text,
    image_licence text,
    licence_reviewed_at timestamp with time zone,
    licence_source_url text,
    licence_note text,
    translation_licence text,
    last_failure_reason text,
    CONSTRAINT event_source_description_licence_valid CHECK (((description_licence IS NULL) OR (description_licence = ANY (ARRAY['PERMITTED'::text, 'PROHIBITED'::text, 'UNCLEAR'::text])))),
    CONSTRAINT event_source_image_licence_valid CHECK (((image_licence IS NULL) OR (image_licence = ANY (ARRAY['PERMITTED'::text, 'PROHIBITED'::text, 'UNCLEAR'::text])))),
    CONSTRAINT event_source_translation_licence_valid CHECK (((translation_licence IS NULL) OR (translation_licence = ANY (ARRAY['PERMITTED'::text, 'PROHIBITED'::text, 'UNCLEAR'::text]))))
);

--
-- Name: event_source_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.event_source ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.event_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: genre_tag; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.genre_tag (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    family text
);

--
-- Name: genre_tag_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.genre_tag ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.genre_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: import_run_field_stats; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.import_run_field_stats (
    id bigint NOT NULL,
    run_id uuid NOT NULL,
    source_id bigint NOT NULL,
    field text NOT NULL,
    events_total integer NOT NULL,
    events_with_value integer NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: import_run_field_stats_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.import_run_field_stats ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.import_run_field_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: promoter; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.promoter (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    website_url text,
    image_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    image_attribution text,
    image_licence_id text,
    image_source_url text,
    description text,
    description_language text,
    description_alt text,
    description_alt_language text,
    reviewed_at timestamp with time zone,
    name_search text GENERATED ALWAYS AS (events.search_text(name)) STORED,
    CONSTRAINT promoter_description_alt_complete CHECK ((((description_alt IS NULL) AND (description_alt_language IS NULL)) OR ((description_alt IS NOT NULL) AND (description_alt_language IS NOT NULL)))),
    CONSTRAINT promoter_description_alt_language_valid CHECK (((description_alt_language IS NULL) OR (description_alt_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT promoter_description_language_valid CHECK (((description_language IS NULL) OR (description_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT promoter_image_attributed CHECK (((image_url IS NULL) OR ((image_attribution IS NOT NULL) AND (image_licence_id IS NOT NULL) AND (image_source_url IS NOT NULL))))
);

--
-- Name: promoter_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.promoter ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.promoter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: venue; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.venue (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    address text,
    city text DEFAULT 'Berlin'::text NOT NULL,
    postal_code text,
    district text,
    latitude numeric(9,6),
    longitude numeric(9,6),
    website_url text,
    image_url text,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    description_language text,
    description_alt text,
    description_alt_language text,
    image_attribution text,
    image_licence_id text,
    image_source_url text,
    venue_types text[] DEFAULT '{}'::text[] NOT NULL,
    capacity integer,
    programme_families text[] DEFAULT '{}'::text[] NOT NULL,
    programme_event_types text[] DEFAULT '{}'::text[] NOT NULL,
    name_search text GENERATED ALWAYS AS (events.search_text(name)) STORED,
    CONSTRAINT venue_capacity_check CHECK ((capacity > 0)),
    CONSTRAINT venue_description_alt_complete CHECK ((((description_alt IS NULL) AND (description_alt_language IS NULL)) OR ((description_alt IS NOT NULL) AND (description_alt_language IS NOT NULL)))),
    CONSTRAINT venue_description_alt_language_valid CHECK (((description_alt_language IS NULL) OR (description_alt_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT venue_description_language_valid CHECK (((description_language IS NULL) OR (description_language = ANY (ARRAY['de'::text, 'en'::text])))),
    CONSTRAINT venue_district_valid CHECK (((district IS NULL) OR (district = ANY (ARRAY['charlottenburg'::text, 'friedrichshain'::text, 'hellersdorf'::text, 'hohenschoenhausen'::text, 'koepenick'::text, 'kreuzberg'::text, 'lichtenberg'::text, 'marzahn'::text, 'mitte'::text, 'neukoelln'::text, 'pankow'::text, 'prenzlauer-berg'::text, 'reinickendorf'::text, 'schoeneberg'::text, 'spandau'::text, 'steglitz'::text, 'tempelhof'::text, 'tiergarten'::text, 'treptow'::text, 'wedding'::text, 'weissensee'::text, 'wilmersdorf'::text, 'zehlendorf'::text])))),
    CONSTRAINT venue_image_attributed CHECK (((image_url IS NULL) OR ((image_attribution IS NOT NULL) AND (image_licence_id IS NOT NULL) AND (image_source_url IS NOT NULL))))
);

--
-- Name: venue_character_tag; Type: TABLE; Schema: events; Owner: -
--

CREATE TABLE events.venue_character_tag (
    venue_id bigint NOT NULL,
    tag text NOT NULL,
    source_url text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT venue_character_tag_source_url_check CHECK ((source_url ~ '^https?://'::text))
);

--
-- Name: venue_id_seq; Type: SEQUENCE; Schema: events; Owner: -
--

ALTER TABLE events.venue ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME events.venue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: artist artist_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.artist
    ADD CONSTRAINT artist_pkey PRIMARY KEY (id);

--
-- Name: artist artist_slug_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.artist
    ADD CONSTRAINT artist_slug_key UNIQUE (slug);

--
-- Name: cached_image cached_image_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.cached_image
    ADD CONSTRAINT cached_image_pkey PRIMARY KEY (id);

--
-- Name: cached_image cached_image_source_url_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.cached_image
    ADD CONSTRAINT cached_image_source_url_key UNIQUE (source_url);

--
-- Name: cached_image_variant cached_image_variant_cached_image_id_width_format_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.cached_image_variant
    ADD CONSTRAINT cached_image_variant_cached_image_id_width_format_key UNIQUE (cached_image_id, width, format);

--
-- Name: cached_image_variant cached_image_variant_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.cached_image_variant
    ADD CONSTRAINT cached_image_variant_pkey PRIMARY KEY (id);

--
-- Name: data_quality_snapshot data_quality_snapshot_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.data_quality_snapshot
    ADD CONSTRAINT data_quality_snapshot_pkey PRIMARY KEY (id);

--
-- Name: data_quality_snapshot data_quality_snapshot_snapshot_date_source_slug_metric_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.data_quality_snapshot
    ADD CONSTRAINT data_quality_snapshot_snapshot_date_source_slug_metric_key UNIQUE (snapshot_date, source_slug, metric);

--
-- Name: event_artist event_artist_event_id_artist_id_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_artist
    ADD CONSTRAINT event_artist_event_id_artist_id_key UNIQUE (event_id, artist_id);

--
-- Name: event_artist event_artist_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_artist
    ADD CONSTRAINT event_artist_pkey PRIMARY KEY (id);

--
-- Name: event_genre_tag event_genre_tag_event_id_genre_tag_id_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_genre_tag
    ADD CONSTRAINT event_genre_tag_event_id_genre_tag_id_key UNIQUE (event_id, genre_tag_id);

--
-- Name: event_genre_tag event_genre_tag_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_genre_tag
    ADD CONSTRAINT event_genre_tag_pkey PRIMARY KEY (id);

--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);

--
-- Name: event_promoter event_promoter_event_id_promoter_id_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_promoter
    ADD CONSTRAINT event_promoter_event_id_promoter_id_key UNIQUE (event_id, promoter_id);

--
-- Name: event_promoter event_promoter_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_promoter
    ADD CONSTRAINT event_promoter_pkey PRIMARY KEY (id);

--
-- Name: event event_slug_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event
    ADD CONSTRAINT event_slug_key UNIQUE (slug);

--
-- Name: event event_source_id_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event
    ADD CONSTRAINT event_source_id_key UNIQUE (source_id);

--
-- Name: event_source event_source_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_source
    ADD CONSTRAINT event_source_pkey PRIMARY KEY (id);

--
-- Name: event_source event_source_slug_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_source
    ADD CONSTRAINT event_source_slug_key UNIQUE (slug);

--
-- Name: genre_tag genre_tag_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.genre_tag
    ADD CONSTRAINT genre_tag_pkey PRIMARY KEY (id);

--
-- Name: genre_tag genre_tag_slug_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.genre_tag
    ADD CONSTRAINT genre_tag_slug_key UNIQUE (slug);

--
-- Name: import_run_field_stats import_run_field_stats_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.import_run_field_stats
    ADD CONSTRAINT import_run_field_stats_pkey PRIMARY KEY (id);

--
-- Name: import_run_field_stats import_run_field_stats_run_id_field_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.import_run_field_stats
    ADD CONSTRAINT import_run_field_stats_run_id_field_key UNIQUE (run_id, field);

--
-- Name: promoter promoter_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.promoter
    ADD CONSTRAINT promoter_pkey PRIMARY KEY (id);

--
-- Name: promoter promoter_slug_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.promoter
    ADD CONSTRAINT promoter_slug_key UNIQUE (slug);

--
-- Name: venue_character_tag venue_character_tag_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.venue_character_tag
    ADD CONSTRAINT venue_character_tag_pkey PRIMARY KEY (venue_id, tag);

--
-- Name: venue venue_pkey; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.venue
    ADD CONSTRAINT venue_pkey PRIMARY KEY (id);

--
-- Name: venue venue_slug_key; Type: CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.venue
    ADD CONSTRAINT venue_slug_key UNIQUE (slug);

--
-- Name: artist_comedian_unread_idx; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX artist_comedian_unread_idx ON events.artist USING btree (id) WHERE ((musicbrainz_match = 'EXACT'::text) AND (wikidata_url IS NOT NULL) AND (comedian IS NULL));

--
-- Name: artist_discogs_unchecked_idx; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX artist_discogs_unchecked_idx ON events.artist USING btree (id) WHERE ((musicbrainz_match = 'NONE'::text) AND (discogs_match = 'UNCHECKED'::text));

--
-- Name: artist_musicbrainz_unchecked_idx; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX artist_musicbrainz_unchecked_idx ON events.artist USING btree (id) WHERE (musicbrainz_match = 'UNCHECKED'::text);

--
-- Name: artist_musicbrainz_unenriched_idx; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX artist_musicbrainz_unenriched_idx ON events.artist USING btree (id) WHERE ((musicbrainz_match = 'EXACT'::text) AND (musicbrainz_enriched_at IS NULL));

--
-- Name: idx_artist_name_search_trgm; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_artist_name_search_trgm ON events.artist USING gin (replace(name_search, ' '::text, ''::text) events.gin_trgm_ops);

--
-- Name: idx_cached_image_content_hash; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_cached_image_content_hash ON events.cached_image USING btree (content_hash) WHERE (content_hash IS NOT NULL);

--
-- Name: idx_cached_image_due; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_cached_image_due ON events.cached_image USING btree (fetched_at, failed_at) WHERE (deleted_at IS NULL);

--
-- Name: idx_data_quality_snapshot_series; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_data_quality_snapshot_series ON events.data_quality_snapshot USING btree (source_slug, metric, snapshot_date);

--
-- Name: idx_event_artist_artist_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_artist_artist_id ON events.event_artist USING btree (artist_id);

--
-- Name: idx_event_artist_event_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_artist_event_id ON events.event_artist USING btree (event_id);

--
-- Name: idx_event_event_date; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_event_date ON events.event USING btree (event_date);

--
-- Name: idx_event_event_source_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_event_source_id ON events.event USING btree (event_source_id);

--
-- Name: idx_event_genre_tag_event_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_genre_tag_event_id ON events.event_genre_tag USING btree (event_id);

--
-- Name: idx_event_genre_tag_genre_tag_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_genre_tag_genre_tag_id ON events.event_genre_tag USING btree (genre_tag_id);

--
-- Name: idx_event_promoter_promoter_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_promoter_promoter_id ON events.event_promoter USING btree (promoter_id);

--
-- Name: idx_event_source_prohibited; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_source_prohibited ON events.event_source USING btree (id) WHERE ((description_licence = 'PROHIBITED'::text) OR (image_licence = 'PROHIBITED'::text));

--
-- Name: idx_event_source_scheduling; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_source_scheduling ON events.event_source USING btree (enabled, status, last_import_at);

--
-- Name: idx_event_source_venue_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_source_venue_id ON events.event_source USING btree (venue_id);

--
-- Name: idx_event_subtitle_search_trgm; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_subtitle_search_trgm ON events.event USING gin (replace(subtitle_search, ' '::text, ''::text) events.gin_trgm_ops);

--
-- Name: idx_event_title_search_trgm; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_title_search_trgm ON events.event USING gin (replace(title_search, ' '::text, ''::text) events.gin_trgm_ops);

--
-- Name: idx_event_venue_id; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_event_venue_id ON events.event USING btree (venue_id);

--
-- Name: idx_genre_tag_family; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_genre_tag_family ON events.genre_tag USING btree (family);

--
-- Name: idx_import_run_field_stats_baseline; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_import_run_field_stats_baseline ON events.import_run_field_stats USING btree (source_id, field, observed_at DESC);

--
-- Name: idx_promoter_name_search_trgm; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_promoter_name_search_trgm ON events.promoter USING gin (replace(name_search, ' '::text, ''::text) events.gin_trgm_ops);

--
-- Name: idx_venue_character_tag_tag; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_venue_character_tag_tag ON events.venue_character_tag USING btree (tag);

--
-- Name: idx_venue_district; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_venue_district ON events.venue USING btree (district);

--
-- Name: idx_venue_name_search_trgm; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_venue_name_search_trgm ON events.venue USING gin (replace(name_search, ' '::text, ''::text) events.gin_trgm_ops);

--
-- Name: idx_venue_programme_event_types; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_venue_programme_event_types ON events.venue USING gin (programme_event_types);

--
-- Name: idx_venue_programme_families; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_venue_programme_families ON events.venue USING gin (programme_families);

--
-- Name: idx_venue_venue_types; Type: INDEX; Schema: events; Owner: -
--

CREATE INDEX idx_venue_venue_types ON events.venue USING gin (venue_types);

--
-- Name: artist trg_artist_name_changed_at; Type: TRIGGER; Schema: events; Owner: -
--

CREATE TRIGGER trg_artist_name_changed_at BEFORE UPDATE OF name ON events.artist FOR EACH ROW WHEN ((old.name IS DISTINCT FROM new.name)) EXECUTE FUNCTION events.set_name_changed_at();

--
-- Name: artist trg_artist_updated_at; Type: TRIGGER; Schema: events; Owner: -
--

CREATE TRIGGER trg_artist_updated_at BEFORE UPDATE ON events.artist FOR EACH ROW EXECUTE FUNCTION events.set_updated_at();

--
-- Name: event_source trg_event_source_updated_at; Type: TRIGGER; Schema: events; Owner: -
--

CREATE TRIGGER trg_event_source_updated_at BEFORE UPDATE ON events.event_source FOR EACH ROW EXECUTE FUNCTION events.set_updated_at();

--
-- Name: event trg_event_updated_at; Type: TRIGGER; Schema: events; Owner: -
--

CREATE TRIGGER trg_event_updated_at BEFORE UPDATE ON events.event FOR EACH ROW EXECUTE FUNCTION events.set_updated_at();

--
-- Name: genre_tag trg_genre_tag_updated_at; Type: TRIGGER; Schema: events; Owner: -
--

CREATE TRIGGER trg_genre_tag_updated_at BEFORE UPDATE ON events.genre_tag FOR EACH ROW EXECUTE FUNCTION events.set_updated_at();

--
-- Name: promoter trg_promoter_updated_at; Type: TRIGGER; Schema: events; Owner: -
--

CREATE TRIGGER trg_promoter_updated_at BEFORE UPDATE ON events.promoter FOR EACH ROW EXECUTE FUNCTION events.set_updated_at();

--
-- Name: venue trg_venue_updated_at; Type: TRIGGER; Schema: events; Owner: -
--

CREATE TRIGGER trg_venue_updated_at BEFORE UPDATE ON events.venue FOR EACH ROW EXECUTE FUNCTION events.set_updated_at();

--
-- Name: cached_image_variant cached_image_variant_cached_image_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.cached_image_variant
    ADD CONSTRAINT cached_image_variant_cached_image_id_fkey FOREIGN KEY (cached_image_id) REFERENCES events.cached_image(id) ON DELETE CASCADE;

--
-- Name: event_artist event_artist_artist_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_artist
    ADD CONSTRAINT event_artist_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES events.artist(id) ON DELETE CASCADE;

--
-- Name: event_artist event_artist_event_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_artist
    ADD CONSTRAINT event_artist_event_id_fkey FOREIGN KEY (event_id) REFERENCES events.event(id) ON DELETE CASCADE;

--
-- Name: event event_event_source_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event
    ADD CONSTRAINT event_event_source_id_fkey FOREIGN KEY (event_source_id) REFERENCES events.event_source(id) ON DELETE SET NULL;

--
-- Name: event_genre_tag event_genre_tag_event_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_genre_tag
    ADD CONSTRAINT event_genre_tag_event_id_fkey FOREIGN KEY (event_id) REFERENCES events.event(id) ON DELETE CASCADE;

--
-- Name: event_genre_tag event_genre_tag_genre_tag_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_genre_tag
    ADD CONSTRAINT event_genre_tag_genre_tag_id_fkey FOREIGN KEY (genre_tag_id) REFERENCES events.genre_tag(id) ON DELETE CASCADE;

--
-- Name: event_promoter event_promoter_event_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_promoter
    ADD CONSTRAINT event_promoter_event_id_fkey FOREIGN KEY (event_id) REFERENCES events.event(id) ON DELETE CASCADE;

--
-- Name: event_promoter event_promoter_promoter_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_promoter
    ADD CONSTRAINT event_promoter_promoter_id_fkey FOREIGN KEY (promoter_id) REFERENCES events.promoter(id) ON DELETE CASCADE;

--
-- Name: event_source event_source_venue_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event_source
    ADD CONSTRAINT event_source_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES events.venue(id);

--
-- Name: event event_venue_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.event
    ADD CONSTRAINT event_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES events.venue(id);

--
-- Name: import_run_field_stats import_run_field_stats_source_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.import_run_field_stats
    ADD CONSTRAINT import_run_field_stats_source_id_fkey FOREIGN KEY (source_id) REFERENCES events.event_source(id) ON DELETE CASCADE;

--
-- Name: venue_character_tag venue_character_tag_venue_id_fkey; Type: FK CONSTRAINT; Schema: events; Owner: -
--

ALTER TABLE ONLY events.venue_character_tag
    ADD CONSTRAINT venue_character_tag_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES events.venue(id) ON DELETE CASCADE;
