{{- if .Values.importer.serviceAccount.create }}
{{- $args := dict "ctx" $ "component" "importer" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "event-junkie.serviceAccountName" $args }}
  labels:
    {{- include "event-junkie.labels" $args | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
