#!/usr/bin/env bash
#
# architecture-diagram.sh — what each environment actually deploys, as sorted text and as a picture.
#
# Usage:
#   scripts/architecture-diagram.sh inventory [env]   # print one environment's inventory
#   scripts/architecture-diagram.sh write [env]       # rewrite docs/architecture/<env>.inventory.txt
#   scripts/architecture-diagram.sh check [env]       # fail when the committed inventory has drifted
#   scripts/architecture-diagram.sh render [env]      # draw the picture into build/architecture/
#   scripts/architecture-diagram.sh environments      # list what <env> can be
#
# Requires: helm and yq for everything but `render`, which also needs uv and Graphviz. Reaches no
# cluster: every verb renders the chart in process from this working tree.
#
# `env` is a directory under deploy/clusters/ and defaults to all of them.
#
# **The committed artifact is the inventory, not the picture.** `docs/ops/PLATFORM_SETUP.md` holds
# hand-written diagrams of what the platform is *for*, and no generator writes those. What a
# generator is good at is noticing that the set of deployed objects changed — so `check` is the
# gate, and it fails with a diff naming the resource that appeared or vanished. That is the prompt
# to look at the hand-written diagram and decide whether it is still true. ADR-034 has the
# reasoning, including why the rendered picture is deliberately not committed.
#
# Each environment is rendered through its own HelmRelease's `spec.values`, which is where
# per-environment configuration lives (#414). Rendering the bare chart is not the same thing and
# does not even work — `database.host` and `database.existingSecret` are `required`.
#
# **Image tags are omitted on purpose.** Every tag falls back to `.Chart.AppVersion`, so a release
# would otherwise rewrite three files and the gate would cry drift at every version bump.
# `cluster-assertions.sh` is what asserts that no HelmRelease pins one.
#
# For a diagram of what is deployed *now* rather than what this tree renders, KubeDiagrams reads a
# live cluster too — but that reaches a cluster, so it is a command an operator types and never a
# verb here:
#
#   kubectl --context <ctx> -n event-junkie get all -o yaml | kube-diagrams -o now.png -

set -euo pipefail

case "${1:-}" in
  -h | --help) awk '/^# Usage:/ { p = 1 } p && !/^#./ { exit } p { sub(/^# ?/, ""); print }' "$0"; exit 0 ;;
esac

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHART_DIR="$REPO_ROOT/deploy/charts/event-junkie"
CLUSTERS_DIR="$REPO_ROOT/deploy/clusters"
DOCS_DIR="$REPO_ROOT/docs/architecture"
BUILD_DIR="$REPO_ROOT/build/architecture"

# Pinned for the same reason the Helm and oxfmt versions are: a renderer that floats is a picture
# that changes without the chart changing. `render` is the only verb that needs it.
KUBEDIAGRAMS_VERSION='0.8.0'

RELEASE_NAME='event-junkie'
NAMESPACE='event-junkie'

die() {
  printf 'architecture-diagram.sh: %s\n' "$1" >&2
  exit 1
}

require() {
  command -v "$1" >/dev/null || die "$1 is required but not on PATH"
}

environments() {
  local file
  for file in "$CLUSTERS_DIR"/*/helm-release.yaml; do
    [[ -f "$file" ]] || continue
    basename "$(dirname "$file")"
  done | sort
}

resolve_environments() {
  local wanted="${1:-}" all
  all="$(environments)"
  [[ -n "$all" ]] || die "no HelmRelease found under $CLUSTERS_DIR"
  if [[ -z "$wanted" ]]; then
    printf '%s\n' "$all"
    return
  fi
  printf '%s\n' "$all" | grep -qxF "$wanted" ||
    die "unknown environment '$wanted'. Known: $(printf '%s' "$all" | tr '\n' ' ')"
  printf '%s\n' "$wanted"
}

# --- The inventory ------------------------------------------------------------------------------
#
# Every line is emitted as `sort-key<TAB>text` and sorted on the key alone, with `sort -s` keeping a
# multi-line resource's own lines in the order yq produced them. The key is `Kind/name`, so kinds
# group themselves and a template renamed or reordered does not move a line.

render_environment() {
  local env="$1" values
  values="$(mktemp)"
  yq -N '.spec.values' "$CLUSTERS_DIR/$env/helm-release.yaml" >"$values"
  # `helm template` writes its "found symbolic link" notices to stderr; the perf files the chart
  # ships are symlinks into perf/, so that notice is expected and is not a failure.
  helm template "$RELEASE_NAME" "$CHART_DIR" --namespace "$NAMESPACE" --values "$values" 2>/dev/null
  rm -f "$values"
}

inventory() {
  local env="$1" rendered
  rendered="$(mktemp)"
  render_environment "$env" >"$rendered"

  [[ -s "$rendered" ]] || die "$env rendered nothing — check deploy/clusters/$env/helm-release.yaml"

  printf '# %s — what deploy/clusters/%s/helm-release.yaml deploys\n' "$RELEASE_NAME" "$env"
  printf '#\n'
  printf '# GENERATED by scripts/architecture-diagram.sh write. Do not edit by hand.\n'
  printf '# Image tags are left out deliberately — see the script header and ADR-034.\n'
  printf '\n'

  # shellcheck disable=SC2016  # $k and $id are yq variables, not shell expansions.
  {
    # Everything, so a resource no template names below still shows up as a line.
    yq -N -r '[.kind, .metadata.name] as $id | ($id | join("/")) + "\t" + ($id | join("/"))' "$rendered"

    yq -N -r 'select(.kind == "Deployment") | ("Deployment/" + .metadata.name) as $k | (
        [$k + "\t  replicas " + (.spec.replicas // "hpa" | tostring)
           + "  strategy " + (.spec.strategy.type // "RollingUpdate")
           + "  serviceAccount " + (.spec.template.spec.serviceAccountName // "default")]
        + [.spec.template.spec.containers[] | $k + "\t  container " + .name
           + "  image " + (.image | sub("@.*$"; "") | sub(":[^:/]*$"; ""))
           + "  ports " + (([.ports[]? | .name + "=" + (.containerPort | tostring)] | join(",")) | sub("^$"; "<none>"))]
      ) | .[]' "$rendered"

    # An HPA owns the replica count, so its range stands where the Deployment's number would.
    yq -N -r 'select(.kind == "HorizontalPodAutoscaler") | ("HorizontalPodAutoscaler/" + .metadata.name) as $k |
      $k + "\t  " + .spec.scaleTargetRef.kind + "/" + .spec.scaleTargetRef.name
        + "  replicas " + (.spec.minReplicas | tostring) + ".." + (.spec.maxReplicas | tostring)
        + "  cpu " + (.spec.metrics[0].resource.target.averageUtilization | tostring) + "%"' "$rendered"

    yq -N -r 'select(.kind == "Service") | ("Service/" + .metadata.name) as $k |
      $k + "\t  " + .spec.type + "  "
        + ([.spec.ports[] | .name + " " + (.port | tostring) + "->" + (.targetPort | tostring)] | join(", "))' "$rendered"

    yq -N -r 'select(.kind == "Ingress") | ("Ingress/" + .metadata.name) as $k | (
        [$k + "\t  class " + (.spec.ingressClassName // "<default>")]
        + [.spec.tls[]? | $k + "\t  tls " + (.hosts | join(",")) + " -> secret/" + .secretName]
        + [.spec.rules[] | .host as $host | .http.paths[] | $k + "\t  " + $host + .path
           + " -> " + .backend.service.name + ":" + (.backend.service.port.number // .backend.service.port.name | tostring)]
      ) | .[]' "$rendered"

    # The selector is what binds a policy to a workload, and is the half of a NetworkPolicy that a
    # rename breaks silently. **Both halves are read**: most of these select by `matchExpressions`,
    # and a `matchLabels`-only reading calls six of them "all pods", which is both wrong and
    # reassuring. The chart's own name and instance labels are dropped — they are on every selector
    # and say nothing about which rule this is.
    yq -N -r 'select(.kind == "NetworkPolicy") | ("NetworkPolicy/" + .metadata.name) as $k |
      ((.spec.podSelector.matchLabels // {}
          | del(.["app.kubernetes.io/name"]) | del(.["app.kubernetes.io/instance"])
          | to_entries | map(.key + "=" + .value))
       + [.spec.podSelector.matchExpressions[]? | .key + " " + .operator + " [" + ((.values // []) | join(",")) + "]"]
       | join(", ")) as $selector |
      $k + "\t  types " + (.spec.policyTypes | join(","))
        + "  selector " + ($selector | sub("^$"; "<all pods>"))' "$rendered"

    # A Traefik Middleware's spec keys are its type — `rateLimit`, `headers`, `inFlightReq`. The
    # values are the chart's to assert; the set of middlewares is the architecture.
    yq -N -r 'select(.kind == "Middleware") | ("Middleware/" + .metadata.name) as $k |
      $k + "\t  " + (.spec | keys | join(","))' "$rendered"
  } | sort -s -t "$(printf '\t')" -k1,1 | cut -d "$(printf '\t')" -f2-

  rm -f "$rendered"
}

# --- The verbs ----------------------------------------------------------------------------------

verb_inventory() {
  local env
  for env in $(resolve_environments "${1:-}"); do
    inventory "$env"
  done
}

verb_write() {
  local env target
  mkdir -p "$DOCS_DIR"
  for env in $(resolve_environments "${1:-}"); do
    target="$DOCS_DIR/$env.inventory.txt"
    inventory "$env" >"$target"
    printf 'wrote %s (%s lines)\n' "${target#"$REPO_ROOT"/}" "$(grep -c . "$target")"
  done
}

verb_check() {
  local env target actual failures=0
  for env in $(resolve_environments "${1:-}"); do
    target="$DOCS_DIR/$env.inventory.txt"
    if [[ ! -f "$target" ]]; then
      printf 'architecture-diagram.sh: %s is missing — run scripts/architecture-diagram.sh write\n' \
        "${target#"$REPO_ROOT"/}" >&2
      failures=$((failures + 1))
      continue
    fi
    actual="$(mktemp)"
    inventory "$env" >"$actual"
    if diff -u --label "$target" --label "$env (rendered now)" "$target" "$actual"; then
      printf '  ok    %s matches what the chart renders\n' "${target#"$REPO_ROOT"/}"
    else
      printf '\narchitecture-diagram.sh: %s has drifted.\n' "${target#"$REPO_ROOT"/}" >&2
      failures=$((failures + 1))
    fi
    rm -f "$actual"
  done

  if [[ "$failures" -gt 0 ]]; then
    printf '\n%d environment(s) out of date. If the change above is intended, run:\n' "$failures" >&2
    printf '  scripts/architecture-diagram.sh write\n' >&2
    printf 'then check that the diagrams in docs/ops/PLATFORM_SETUP.md are still true.\n' >&2
    exit 1
  fi
}

verb_render() {
  require uv
  command -v dot >/dev/null || die 'Graphviz is required for render (brew install graphviz)'

  # pygraphviz compiles against Graphviz's headers, and finds them on a Mac only when told where
  # Homebrew put them. Harmless everywhere else: an empty prefix leaves both variables untouched.
  local prefix
  prefix="$(brew --prefix graphviz 2>/dev/null || true)"
  if [[ -n "$prefix" ]]; then
    export CFLAGS="${CFLAGS:-} -I$prefix/include"
    export LDFLAGS="${LDFLAGS:-} -L$prefix/lib"
  fi

  local env rendered
  mkdir -p "$BUILD_DIR"
  for env in $(resolve_environments "${1:-}"); do
    rendered="$BUILD_DIR/$env.yaml"
    render_environment "$env" >"$rendered"
    uvx --from "KubeDiagrams==$KUBEDIAGRAMS_VERSION" kube-diagrams \
      --embed-all-icons -f svg -o "$BUILD_DIR/$env.svg" "$rendered"
    printf 'wrote %s\n' "${BUILD_DIR#"$REPO_ROOT"/}/$env.svg"
  done

  # Said once, here, because the picture looks like something to commit and is not: the node ids are
  # random per run, so two renders of one input differ in hundreds of lines. ADR-034.
  printf '\nThese are scratch files. The committed artifact is docs/architecture/*.inventory.txt.\n'
}

# --- Dispatch -----------------------------------------------------------------------------------

verb="${1:-}"
shift || true

case "$verb" in
  inventory | write | check) require helm; require yq; "verb_$verb" "${1:-}" ;;
  render) require helm; require yq; verb_render "${1:-}" ;;
  environments) environments ;;
  '') die 'no verb. Try --help' ;;
  *) die "unknown verb '$verb'. Try --help" ;;
esac
