apiVersion: v1
kind: Secret
metadata:
    name: events-db
    namespace: event-junkie
type: Opaque
data:
    username: ENC[AES256_GCM,data:9mEjDZeFmDc=,iv:xqaT0lGdTl6EhvSHavJaUyKDJ3a1g7eb1ysNnd8Z3is=,tag:KcyxzeJt+3E5FSnNamSDsw==,type:str]
    password: ENC[AES256_GCM,data:+/G2DTgU3C/XCyFRXEGvhbLDqQXENHyhOyaa53u6wkwOyEExgImm4lW3jMRWKOZiSGzy5a9nSMI=,iv:p0drt3wG4RkzRIZZI3LAxH4mbqY+1Dwn7dSW7nHGwb4=,tag:otOZeIiUMsyNPNWz4cTCOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtejYvT2hIUXlQR3BQSmdG
            RGc1ejhsYkIrOGttdlRNOEpkcnFRTkdJWEVBCmMxaTEvaTROSWFXTUtvZlBoYlNs
            RlFrQUQrZXRiUGZ5QTZXVUFhQ1R5VWsKLS0tIFJHcUF1bGI3Y2Yxa2FkcW9aVUZC
            bzBodXJKNitFR1RZb2lIa3JSaXhpVGsKC0vKf59gEn0q0+ySLonx/ptYAEDDwRYa
            qxckeMU64pB9PH2rUbmr6XMGdoVqc39ixxS5kmpwZJIqA5CUqMM3ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ngml2xyqzg8kltjzytsufgqj8wl5rz5r3zs4p90jdcsy74srfesj74nnt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T00:18:18Z"
    mac: ENC[AES256_GCM,data:+TI4Ttleuy9W5IJdFs0N4pVWOl14h4GDgCFFPXzc41fuFhf5xiwX0kgDsSi+6nnnCrHHqc69jDjbmOHp8Jyp/fYkQXLXzW5Kkl5gbgy89hlO0pEIE6bEuiQ7uopKpPFw4FjQcrXRjJ5xegCp2JdT/JT+1PqPtebBW0kLa/Ni5DA=,iv:d+x8q6Gv/fbq0uJ7YxAiW1skR+D68rbrpLYlrkng/d4=,tag:pIiUUzFtXeSLpku0EK+hZg==,type:str]
    version: 3.13.3
