apiVersion: v1
data:
    password: ENC[AES256_GCM,data:RFW7WdZw5a1QEi9iqCQLEps4SqcR6clQhpt/MfKWKa9Meipk6CK85UDdX6dt/tWMFZX+WNxIGQg=,iv:6lgKeTH1ZCXUsy4qT1YHmlATusmBEoRICrmoBIm9Y0o=,tag:k+0vZdQrZi/UMouYvl1XUw==,type:str]
    username: ENC[AES256_GCM,data:0icwh5oSplg=,iv:NJFkxHSHCgUEJSuLbAVjo0VTI4wM3tGbl0+rNjHP6EY=,tag:UJynrfGc46JOAo7O+tu5Uw==,type:str]
kind: Secret
metadata:
    name: events-db
    namespace: event-junkie
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSzMyQ3hqK2t2MzJLU1Fh
            NC95R0lZMEgxNmp2K0RCWk1zWUpXZHR1a3lBClFtLzVNcEhPSXhpUGlzNzRJSTNH
            NHpxRm5jUDF3bnlNcG1UTHMwRlRPWEEKLS0tIDgySTJvc2RlRUh6aDRRTDA5ei9p
            M3JHUzVPUUdyMFJ0ZzZTejkzT29LSjgK6Z9ghSK9uL27EqAtcWoSf4LnJzCjHeHP
            X9ePtFuek/SxfYeX7ltMi2hB4C48ArpbblKEM7RmtMOLdaI9ePE1pA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15ngml2xyqzg8kltjzytsufgqj8wl5rz5r3zs4p90jdcsy74srfesj74nnt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T09:46:12Z"
    mac: ENC[AES256_GCM,data:lShj0Frr9Px/dcFkw2JpFB5y9vErQQnlpB4Cy+uKg2cCkN6wwNHGHqTemxuQpmIemptA6AG0JC94hqV4tu/CsLkb7SrZ9ICxWRVa9iWgaghlemPtVIpL0PPeGN/igw8PgiGglPNumEERrznuXZIlpm5MUA8S/x4KuDHm4AQ2A0o=,iv:5GLdrzRV1nEtviNXS7ajsFLcWm9egGJsjzGLcBq+f+w=,tag:xf4IMuioiFAL6vQCRqPpgA==,type:str]
    version: 3.13.3
