/**
 * Outbound links to the project's GitHub repository, in one module so the header, the footer and
 * the version line cannot drift onto different URLs (docs/LEGAL.md §3).
 */

export const REPOSITORY_URL = 'https://github.com/enorm-labs/event-junkie'

/** The Apache-2.0 licence text this project is released under. */
export const LICENSE_URL = `${REPOSITORY_URL}/blob/main/LICENSE`

/** Issue list — where "report wrong data" sends people. */
export const ISSUES_URL = `${REPOSITORY_URL}/issues`

/**
 * The new-issue chooser rather than a blank form, so it presents the issue templates.
 */
export const NEW_ISSUE_URL = `${REPOSITORY_URL}/issues/new/choose`

/** Releases page — the changelog, generated by .github/release.yml. */
export const RELEASES_URL = `${REPOSITORY_URL}/releases`

/** Contribution guide. GitHub renders the Markdown, so this needs no page of our own. */
export const CONTRIBUTING_URL = `${REPOSITORY_URL}/blob/main/CONTRIBUTING.md`

/**
 * A released version: a plain `major.minor.patch` triple and nothing else. Stated positively
 * (#502): the footer used to test `version.includes('-SNAPSHOT')`, and that spelling never
 * reaches a browser, since `release.yml` builds every artifact with what `scripts/version.sh
 * compute` produces, `0.1.1-snapshot.20260817180146.g787d7d0`, lowercase and dot-separated. Every
 * deployed build linked to a tag that 404s. The same regex as production's `semverFilter` in
 * `deploy/clusters/production/oci-repository.yaml`, deliberately: two definitions of "a release"
 * would drift.
 */
const RELEASE_VERSION = /^\d+\.\d+\.\d+$/

export function isReleaseVersion(version: string | null | undefined): boolean {
  return typeof version === 'string' && RELEASE_VERSION.test(version)
}

/**
 * Permalink to a single release, or `null` when this version was never released, so the
 * decision sits next to the rule that defines it rather than in the template.
 */
export function releaseTagUrl(version: string | null | undefined): string | null {
  return isReleaseVersion(version) ? `${RELEASES_URL}/tag/v${version}` : null
}

/** Permalink to a single commit. Takes the full SHA; the footer displays a short form. */
export function commitUrl(sha: string): string {
  return `${REPOSITORY_URL}/commit/${sha}`
}
