/**
 * Outbound links to the project's GitHub repository.
 *
 * One module so the header, the footer and (from Phase 3) the version line cannot drift onto
 * different URLs — the header previously carried its own `REPOSITORY_URL` constant.
 * See docs/LEGAL.md §3.
 */

export const REPOSITORY_URL = 'https://github.com/enorm-labs/event-junkie'

/** The Apache-2.0 licence text this project is released under. */
export const LICENSE_URL = `${REPOSITORY_URL}/blob/main/LICENSE`

/** Issue list — where "report wrong data" sends people. */
export const ISSUES_URL = `${REPOSITORY_URL}/issues`

/**
 * The new-issue chooser rather than a blank form, so it presents the issue templates once they
 * exist (Phase 6). Until then GitHub falls back to the blank form, which still works.
 */
export const NEW_ISSUE_URL = `${REPOSITORY_URL}/issues/new/choose`

/** Releases page — the changelog, generated by .github/release.yml. */
export const RELEASES_URL = `${REPOSITORY_URL}/releases`

/** Contribution guide. GitHub renders the Markdown, so this needs no page of our own. */
export const CONTRIBUTING_URL = `${REPOSITORY_URL}/blob/main/CONTRIBUTING.md`

/** Permalink to a single release, for the footer's version line (Phase 3). */
export function releaseTagUrl(version: string): string {
  return `${RELEASES_URL}/tag/v${version}`
}

/** Permalink to a single commit. Takes the full SHA; the footer displays a short form. */
export function commitUrl(sha: string): string {
  return `${REPOSITORY_URL}/commit/${sha}`
}
