package de.norm.events.docs

import de.norm.events.EVENTS_SCHEMA
import io.kotest.assertions.withClue
import io.kotest.matchers.shouldBe
import org.flywaydb.core.Flyway
import org.junit.jupiter.api.Test
import org.testcontainers.postgresql.PostgreSQLContainer
import java.io.File

/**
 * `docs/architecture/schema.sql` is the schema a fresh database has after every migration (#2477).
 *
 * It gives the one-file view a Flyway baseline would give, without changing how a cluster migrates (ADR-005 § Baseline).
 * A plain container and Flyway, not a Spring context, so the test adds no cached context.
 *
 * Rewrite the file with `./gradlew :events-importer:updateSchemaDump`.
 */
class SchemaDumpTest {
    @Test
    fun `schema_sql matches a freshly migrated database`() {
        val file = schemaFile()
        val expected = HEADER + normalise(dump())
        val actual = if (file.isFile) file.readText() else ""

        if (actual != expected && System.getProperty(UPDATE_PROPERTY) == "true") {
            file.writeText(expected)
            return
        }

        withClue(
            "${file.name} no longer matches the migrations. Rewrite it with `./gradlew :events-importer:updateSchemaDump`, " +
                "then read the field tables in docs/DATA_MODEL.md: nothing generates those."
        ) {
            actual shouldBe expected
        }
    }

    private fun dump(): String =
        PostgreSQLContainer(POSTGRES_IMAGE).use { postgres ->
            postgres.start()
            Flyway
                .configure()
                .dataSource(postgres.jdbcUrl, postgres.username, postgres.password)
                .schemas(EVENTS_SCHEMA)
                .load()
                .migrate()
            val result =
                postgres.execInContainer(
                    "pg_dump",
                    "--username=${postgres.username}",
                    "--dbname=${postgres.databaseName}",
                    "--schema-only",
                    "--schema=$EVENTS_SCHEMA",
                    "--extension=*",
                    "--exclude-table=$EVENTS_SCHEMA.flyway_schema_history",
                    "--no-owner",
                    "--no-privileges"
                )
            withClue("pg_dump failed: ${result.stderr}") { result.exitCode shouldBe 0 }
            result.stdout
        }

    /**
     * Drops what changes between runs or versions without changing the schema: the version banner,
     * the session `SET`s and the random `\restrict` token pg_dump writes since 18.0.
     */
    private fun normalise(dump: String): String =
        dump
            .lines()
            .filterNot { line -> VOLATILE.any { it.containsMatchIn(line) } }
            .joinToString("\n")
            .replace(EMPTY_COMMENT_BLOCK, "")
            .replace(Regex("\n{3,}"), "\n\n")
            .trim() + "\n"

    private fun schemaFile(): File {
        val root = File("..").absoluteFile.normalize()
        withClue("expected the repository root at $root — this test rewrites a file outside its own module") {
            File(root, "settings.gradle.kts").isFile shouldBe true
        }
        return File(root, "docs/architecture/schema.sql")
    }

    private companion object {
        const val POSTGRES_IMAGE = "postgres:18.3-alpine"
        const val UPDATE_PROPERTY = "updateSchemaDump"

        const val HEADER =
            "-- Generated by SchemaDumpTest from a database migrated to the newest version. Do not edit by hand.\n" +
                "-- Rewrite with ./gradlew :events-importer:updateSchemaDump.\n\n"

        val VOLATILE =
            listOf(
                Regex("""^-- (PostgreSQL database dump|Dumped (from|by)) """),
                Regex("""^-- PostgreSQL database dump( complete)?$"""),
                Regex("""^\\(un)?restrict """),
                Regex("""^SET """),
                Regex("""^SELECT pg_catalog\.set_config\(""")
            )

        /** The `--` frame left behind once the banner line inside it is dropped. */
        val EMPTY_COMMENT_BLOCK = Regex("(?m)^--\n--$\n?")
    }
}
